nodejs/node-core-utils

- bin/metadata.js
- lib/metadata_gen.js
- lib/pr_checker.js
- queries/PR.gql
Just making sure we are not stepping on each other's toes... @MylesBorins @addaleax
> refactor bin and check, implement 48-hour wait

- lib/auth.js
- lib/request.js
- try/catch reading + parsing the config file
- If config data is missing/invalid, prompt the user for data
> More advanced auth

- README.md
> add npm badge to README

- .eslintignore
- bin/metadata.js
- lib/auth.js
- package.json
```
> eslint . "--fix"
/node-core-utils/lib/auth.js
47:10  error  Redundant use of `await` on a return value      no-return-await
70:5   error  Return statement should not contain assignment  no-return-assign
/node-core-utils/lib/request.js
38:7  error  'totalCount' is assigned a value but never used  no-unused-vars
```
We have 3 errors. What do you think?(accept rules, etc...)
But `totalCount` seems to be used 🤔
> chore: introduce eslint

- .eslintrc
- .gitignore
- lib/auth.js
- package.json
- test/fixtures/run-auth.js
- test/unit/auth.test.js
Really no idea what the current cool™ testing framework is these days, I always use mocha but it has its downsides – this just adds a single file that can run as a node script.
It’s also one of the things that’s slightly harder to test, so I feel responsible for writing the test for it ;)
@joyeecheung Could you enable Travis for this repo?
> add first tests :)

- .travis.yml
> use `coverage-all` as the CI test script

- lib/metadata_gen.js
- test/unit/metadata_gen.test.js
This is the convention of node-review.
> metadata: put fixes and refs before reviewers

- .gitignore
- test/intergration/collaborators.test.js
- test/unit/auth.test.js
Fixes: https://github.com/joyeecheung/node-core-utils/issues/32
> Make auth tests work with async/await

- lib/pr_checker.js
- package.json
- test/fixtures/index.js
- test/fixtures/reviewers_rejected.json
- test/fixtures/reviews_rejected.json
- test/fixtures/semver_major_pr.json
- test/unit/metadata_gen.test.js
- test/unit/pr_checker.test.js
- test/unit/reviews.test.js
Also merge `checkReviewers` and `checkReviews` because their purposes don't really differ that much..
> Test PR checker

- lib/logger.js
- test/unit/logger.test.js
In order to be consistent with [ERROR] label.
> logger: add red color to [STACK] and [DATA]

- test/unit/auth.test.js
Extends the timeout from `1000` to `1500`
Fixes: https://github.com/joyeecheung/node-core-utils/issues/49
> fix flakiness of auth.test.js

- package.json
It can be useful to local testing.
https://istanbul.js.org/docs/advanced/alternative-reporters/
> update package.json with both html and text coverage reports

- README.md
Thanks to https://github.com/joyeecheung/node-core-utils/pull/80 the appveyor builds are now passing!
> doc: add appveyor badge

- lib/pr_checker.js
- test/unit/pr_checker.test.js
Hey team!
Quick addition, title is explicit enough I think.
Open to suggestions!
> Skip wait check when label 'code-and-learn' is found, testing

- lib/pr_checker.js
- test/fixtures/data.js
- test/fixtures/multiple_commits_after_ci.json
- test/unit/pr_checker.test.js
> PRChecker: limit num of last commits that gets logged.

- lib/request.js
> request: user-friendly error rather than error json

- CONTRIBUTING.md
> code of conduct: update link to code of conduct

- README.md
Fixes: #112 
Refs: https://github.com/nodejs/node/blob/master/BUILDING.md#supported-platforms-1
> readme: add note about `winpty` while using  git bash

- components/metadata.js
- lib/args.js
- lib/collaborators.js
- lib/pr_data.js
- test/unit/args.test.js
- test/unit/collaborators.test.js
- test/unit/pr_data.test.js
So commands like `get-metadata --repo llnode --readme ../node/README.md 152` work
> lib: specify readme from a file

- lib/pr_checker.js
- lib/queries/PR.gql
- test/fixtures/closed_pr.json
- test/fixtures/data.js
- test/fixtures/merged_pr.json
- test/unit/pr_checker.test.js
Fixes: https://github.com/nodejs/node-core-utils/issues/137
> Warn if PR if closed or merged

- package-lock.json
- package.json
It think this slipped through since, during devlopment we do have that package installed.
Fixes: https://github.com/nodejs/node-core-utils/issues/145
> Add rimraf as a dependency.

- README.md
- lib/file.js
- lib/session.js
> Fix ncu-config

- lib/landing_session.js
I made the mistake to use "reword" more than once by habit.
> git-node-land: mention the "edit" rebase option

- lib/queries/Team.gql
- lib/team_info.js
- test/unit/team_info.test.js
> ncu-team: retrieve the whole team

- lib/landing_session.js
Fixes: https://github.com/nodejs/node-core-utils/issues/191
> git-node: execute local core-validate-commit

- package.json
Fixes: https://github.com/nodejs/node-core-utils/issues/195
> package.json: remove "main" field

- test/fixtures/data.js
- test/fixtures/pr_with_fixes_cross.json
- test/unit/metadata_gen.test.js
Fixes: https://github.com/nodejs/node-core-utils/issues/75
> test: add tests for cross-repository/cross-owner fixes

- lib/ci.js
- test/fixtures/comments_with_ci.json
- test/unit/ci.test.js
- test/unit/pr_checker.test.js
I still need to add test for this.
> CI Fix node-commit-linter-lite not being detected 

- lib/auth.js
- lib/config.js
- lib/ncurc_path.js
> config: use correct file if XDG_CONFIG_HOME is set

- lib/pr_checker.js
- test/unit/pr_checker.test.js
This PR is for fixing `nodejs/node-core-utils` Issues [#215 Weird weekend detection](https://github.com/nodejs/node-core-utils/issues/215).
@cPhost Please review it. If you want I can add more test cases on some of the potentially similar places in this project repo.
> #215 Weird weekend detection fixed

- package-lock.json
Mostly to udpate core-validate-commit to 3.5.1
Refs: https://github.com/nodejs/core-validate-commit/pull/26
> package: update package-lock.json

- components/git/epilogue.js
- docs/git-node.md
- lib/landing_session.js
> remove outdated instructions

- README.md
> Add a link to `ncu-ci` docs in README

- lib/landing_session.js
- lib/session.js
When `git am` failed, we should allow the user to continue amending if they've fixed the conflict.
> git-node: better state handling during APPLYING

- lib/ci/ci_failure_parser.js
- lib/ci/ci_result_parser.js
Also added a few cases of build failure patterns
> ci: parse console if all sub builds succeed in a failed build

- lib/pr_checker.js
- test/unit/pr_checker.test.js
Fixes: https://github.com/nodejs/node-core-utils/issues/279
> git: warn instead of error in case of wrong git config

- docs/git-node.md
Refs: https://github.com/nodejs/node-core-utils/issues/291
> docs: clarify git-node configuration

- .eslintignore
- components/git/wpt.js
- docs/git-node.md
- lib/ci/ci_result_parser.js
- lib/ci/ci_type_parser.js
- lib/comp.js
- lib/github/tree.js
- lib/queries/LastCommit.gql
- lib/queries/TreeEntries.gql
- lib/reviews.js
- lib/utils.js
- lib/wpt/harness.js
- lib/wpt/index.js
- lib/wpt/templates/README.md
- test/unit/comp.test.js
Refs: https://github.com/nodejs/node/issues/23192
> git-node: initial implementation of `git node wpt`

- components/git/v8.js
- docs/git-node.md
- lib/update-v8/backport.js
- lib/update-v8/index.js
- package-lock.json
- package.json
- Add support for incomplete SHA as input
- Add support for multiple SHAs to be combined
I'd like this to be merge quickly so I can work on a fix for https://github.com/nodejs/node-core-utils/issues/303 on top of it.
> v8: make backport command better

- lib/auth.js
- lib/cli.js
- test/fixtures/run-auth-github.js
- test/unit/auth.test.js
- test/unit/cli.test.js
Combined with https://github.com/nodejs/node-core-utils/pull/314 this should make the tests pass on Windows with Travis. See https://travis-ci.org/joyeecheung/node-core-utils/jobs/462560512
> lib: replace EOL with LF

- components/git/backport.js
- components/git/sync.js
- docs/git-node.md
- lib/backport_session.js
- lib/cli.js
- lib/landing_session.js
- lib/links.js
- lib/session.js
- lib/sync_session.js
Demo of `git node backport`: https://asciinema.org/a/221244
Demo of `git node sync`: https://asciinema.org/a/221230
> git: initial implementation of `git node backport` and `git node sync`

- lib/update-v8/majorUpdate.js
Remove Python comments from the object before evaluating it.
Refs: https://github.com/v8/v8/blob/85017f042855d78ec6d87f00f75e12d966241f1b/DEPS#L112
> v8: fix reading DEPS file

- lib/pr_checker.js
- test/fixtures/commits_after_ci.json
- test/unit/pr_checker.test.js
Fixes: https://github.com/nodejs/build/issues/1760
> pr_checker: fix discovery of most recent CI

- docs/git-node.md
> doc: update prerequisite of git node v8 on macos

- .travis.yml
> travis: add node 12 & remove sudo: false 

- .travis.yml
Remove node v8 and v11 from the travis yaml and add node v13
> travis: add node 13 and remove 8 and 11

- bin/git-node
> feat(git-node): handle unknown commands

- lib/prepare_release.js
Refs: https://github.com/nodejs/node/blob/cf888ac105ffd02bbceef02c16d0df548676abd1/doc/guides/releases.md#5-create-release-commit
> fix: add missing comma in release commit title

- components/git/wpt.js
These are now needed by the WPT idl harness
> git-node: update dom.idl and html.idl

- lib/landing_session.js
Refs: https://github.com/nodejs/node-core-utils/issues/425
> git-node: automatically remove temporary files

- docs/ncu-ci.md
This PR improves and reworks documentation for `ncu-ci` to add examples and remove ambuguity about each command.
cc @mmarchini @targos @BridgeAR
> docs: improve ncu-ci docs

- package.json
Updates mocha to the latest release ❤️
> chore: update mocha to v8.x

- components/git/status.js
- docs/git-node.md
Closes https://github.com/nodejs/node-core-utils/issues/228.
New output:
```console
node on git:master ❯ g node status                                             11:32AM
✔  Landing session in progress
PR:        https:/github.com/nodejs/node/pull/34800
State:     AMENDING
Username:  codebytere
Upstream:  upstream
Branch:    master
```
> feat(git-node): add git-node status

- lib/cli.js
- lib/session.js
- package.json
- test/unit/prepare_release.test.js
I did not update `ghauth` in this PR because it is not trivial.
> chore: update dependencies

- .github/workflows/commitlint.yml
- .github/workflows/nodejs.yml
- .github/workflows/release-please.yml
- .github/workflows/stale.yml
- Use the same YAML structure everywhere
- Use actions/setup-node@v2-beta
- Add Node.js 15.x to the test matrix
- Add windows-latest to the test matrix
- Update release-please-action to v2.5.7
- Update stale action to v3
> chore: update and normalize GitHub workflows

- components/git/land.js
- components/metadata.js
- lib/landing_session.js
- lib/pr_checker.js
- lib/session.js
Fixes: https://github.com/nodejs/node-core-utils/issues/527
> feat: make --checkCI optionable for git-node-land

- test/unit/auth.test.js
The test is failing on Windows in CI.
Simplify it to make debugging it easier.
> test: simplify auth.test.js

- lib/landing_session.js
- lib/utils.js
- package.json
Also make the output easier to copy and paste.
> feat: suggest `gh pr` commands to finish landing

- lib/prepare_release.js
Found while preparing v17.1.0.
> fix: add missing new line in changelog

- lib/auth.js
- test/unit/auth.test.js
Fixes: https://github.com/nodejs/node-core-utils/issues/617
Refs: https://github.blog/changelog/2021-03-31-authentication-token-format-updates-are-generally-available/
> fix: update permitted GitHub token characters

- .github/workflows/commitlint.yml
- .github/workflows/nodejs.yml
- .github/workflows/release-please.yml
And don't share `GITHUB_TOKEN` when not necessary.
> chore: update GitHub actions

- lib/update-v8/majorUpdate.js
- lib/update-v8/minorUpdate.js
- lib/update-v8/util.js
Refs: https://github.com/nodejs/node-core-utils/pull/675
> fix: use correct V8 tag for minor updates

- README.md
Update the build shield badge to the new format.
Refs: https://github.com/badges/shields/issues/8671
> docs: update build shield badge

- lib/prepare_release.js
Refs: https://github.com/nodejs/node-core-utils/issues/686
> fix: enforce markdown when generating changelog

- lib/prepare_release.js
Refs: https://github.com/nodejs/node-core-utils/issues/686
> fix: update changelog list when preparing release

- README.md
- bin/git-node.js
- bin/ncu-ci.js
- bin/ncu-config.js
- bin/ncu-team.js
> feat: add autocomplete

- lib/update-v8/constants.js
Refs: https://github.com/nodejs/node-v8/issues/211
Refs: https://github.com/v8/v8/commit/fa7521ef3eb6c69fa398809e7ce4a869c94661fa
> feat: add Abseil to V8 deps

- lib/update-v8/constants.js
Refs: https://github.com/v8/v8/commit/6196de89e304b22a007397fcd7424d29d18dbd09
Refs: https://github.com/v8/v8/commit/8fcd3f809ba5c71f7a29bc6623c1f93a9eac72fe
> feat: add fp16 to V8 deps

- lib/prepare_security.js
Fixes: https://github.com/nodejs-private/security-release/issues/6
Fixes: https://github.com/nodejs-private/security-release/issues/8
@RafaelGSS
> feat: add link to title and to json

- components/git/security.js
- lib/prepare_security.js
- lib/security-release/security-release.js
- lib/update_security_release.js
Fixes: https://github.com/nodejs-private/security-release/issues/7
@RafaelGSS
> feat: add report to vulnerabilities.json

- lib/prepare_security.js
Fixes: https://github.com/nodejs-private/security-release/issues/10
@RafaelGSS  do we also want to add name?
> feat: add reporter username to vulnerability

- components/git/security.js
- docs/git-node.md
- lib/update_security_release.js
This feature allows to remove a report from vulnerabilities.json based on the id
> feat: remove report from vulnerabilities.json

- lib/github/templates/security-pre-release.md
ref: https://github.com/nodejs/nodejs.org/pull/6574#discussion_r1541792355
> lib: remove double space on title

- lib/github/templates/security-pre-release.md
- lib/security_blog.js
Fixes: https://github.com/nodejs-private/security-release/issues/17
Refs: https://github.com/nodejs/nodejs.org/pull/6574/commits
> fix: adjust pre-sec-release template lint

- lib/prepare_security.js
Fixes: https://github.com/nodejs-private/security-release/issues/23
@RafaelGSS
> feat: add releaseDate to json

- lib/ci/run_ci.js
- test/unit/ci_start.test.js
Which made me realize the code needs to actually fetch the review data from GitHub API to work correctly.
> fix(ncu-ci): fix missing `await` causing all CI requests to be rejected

- lib/utils.js
Fixes: https://github.com/nodejs/node-core-utils/issues/605
> fix: define a fallback editor

- lib/prepare_security.js
- lib/request.js
- lib/security-release/security-release.js
Fixes: https://github.com/nodejs-private/security-release/issues/30
> lib: add PR_URL to vuln.json and fetch from H1

- lib/github/templates/security-pre-release.md
Fixes: https://github.com/nodejs-private/security-release/issues/28
cc: @joyeecheung
> lib: add EOL warning to pre sec release template

- components/git/security.js
> fix: adjust pre-release description

- lib/security_blog.js
Fixes: https://github.com/nodejs-private/security-release/issues/36
> lib: sort affected versions ASC

- lib/prepare_security.js
- lib/security-release/security-release.js
Fixes: https://github.com/nodejs-private/security-release/issues/20
> feat: update next-security-release folder on cleanup

- lib/update-v8/constants.js
Refs: https://github.com/v8/v8/commit/7384d3f97e671c4719ba3fcce2dd7aa5e7a67136
> feat(v8): add fast_float to V8 deps

- lib/prepare_release.js
Refs: https://github.com/nodejs/node-core-utils/pull/862#discussion_r1826384266
> update: fix default answers in release --prepare

- components/git/release.js
- docs/git-node.md
- lib/prepare_release.js
This will enable us to automate release proposal
creation: https://github.com/nodejs/security-wg/issues/860
> feat: add --releaseDate to git node release

- components/git/wpt.js
CC @panva 
Followup https://github.com/nodejs/node/pull/54593/files#diff-044c4e3128d6bcf139f31a36cf054f2e59954367d4493e1c1b1a42d7b9d88067
> fix(git-node): followup fix for supported wpt jsons

- lib/security_blog.js
This fixes a lint error when generating the announcement posts
> fix: add line break when updating banner

- lib/update_security_release.js
Found this while generating the latest CVEs
> fix: adjust cve request generation

- lib/security_blog.js
Fixes: https://github.com/nodejs-private/security-release/issues/45
> fix: sort impacted versions DESC

- lib/security_blog.js
Found this while generating the post-release script
> fix: fix post-release dependency updates generation

- lib/update-v8/constants.js
Refs: https://github.com/v8/v8/commit/616c87580c06e76d991c06213530e5ac0043c314
Refs: https://github.com/v8/v8/commit/e3204d589e7911bd2ee75784bec2f9c9e482bbcb
> feat(v8): add highway to V8 deps

- lib/queries/Reviews.gql
- lib/reviews.js
Looks like I forgot to commit that in #911, resulting in broken CQ (https://github.com/nodejs/node/pull/57620#issuecomment-2760568603)
> fix(git-node): retrieve reviewed commit info

- .npmrc
- README.md
- use `npm ci` instead of `npm install`
- Add .npmrc with ignore-scripts=true
> fix(deps): update installation process for local development
