nodejs/node-core-utils

bin/metadata.js
i.e. make `get-metadata https://github.com/nodejs/node/pull/16489` work
=> allow passing full URLs on the command line

bin/metadata.js, lib/ci.js, lib/pr_checker.js, lib/reviews.js, queries/Reviews.gql
Example: https://github.com/nodejs/node/pull/15565#pullrequestreview-72674483
=> detect CI links in reviews

.travis.yml
Right now the time it takes to run a test is not large but in future if the npm packages increases the build will take longer doing so will make build quicker.
=> travis: cache node_modules so faster build

lib/logger.js, test/fixtures/capture_stdout.js, test/unit/logger.test.js
Adds a fixture to capture the stdout output
in order to make tests as real as possible.
Please, review it. Thanks!
=> add tests to `lib/logger`

lib/logger.js, test/unit/logger.test.js
This PR contains a fix for JSON data not using EOL and temporary workarounds for missing upstream support within pino, see https://github.com/pinojs/pino/issues/326.
=> Fix logger test failures on Windows

test/unit/metadata_gen.test.js
On Windows, the strings mismatched due to different EOLs. (Template string literals always use LF while the metadata generator emits CRLF.)
=> Fix metadata generation test on Windows

lib/logger.js, package.json, test/unit/logger.test.js
This patch ensures proper EOL handling on Windows, but needs https://github.com/pinojs/pino/pull/327 to be merged and released to work.
Refs: https://github.com/joyeecheung/node-core-utils/pull/47
=> Properly use EOL on Windows when logging

bin/metadata.js, lib/pr_data.js, queries/PR.gql, test/fixtures/first_timer_pr.json, test/fixtures/semver_major_pr.json, test/fixtures/test_logger.js, test/unit/pr_data.test.js
So this adds three intro lines of logs that are basically the github PR header (title + pr num, commit author, commit count, branch info + labels). I would like to have this info available and I believe there was a request for it in the issues too.
It's implemented on the PRData class which made the most sense to me as it just logs information from that class. Also, we might want to use this on other targets (such as land-pr).
Tests are included.
=> add an intro section with useful info

appveyor.yml, package.json
cache node_modules
this still does not fix test failures of auth but rather exits the
test so joyeecheung does not have to cancel the build manually
=> mocha, appveyor: add flag --exit so appveryor build does not get stuck

lib/pr_checker.js, test/unit/pr_checker.test.js
What it says in the PR title, really. This will be useful down the line when we're implementing different targets such as `land-pr` that need to know the status.
=> expand checker methods to return check status

CONTRIBUTING.md, LICENSE, README.md
Refs: https://github.com/joyeecheung/node-core-utils/issues/59
The contributing guide is largely borrowed from the llnode one, although during this patch I noticed that one needs update as well...that one was largely borrowed from the node core one, I dropped a few requirements e.g. wrapping commit message header line in 50 chars because they feel a bit lengthy to me.
=> doc: add contributing guide and license

README.md, lib/auth.js, package.json, test/fixtures/run-auth.js, test/unit/auth.test.js
This enables the use of [rvagg/ghauth](https://github.com/rvagg/ghauth) for first-time users instead of a user supplied token that creates the `.ncurc` file. I think this is a slightly nicer user experience. (If they already have a token, creating a `~/.ncurc` file from the terminal seems easy...)
Didn't have to change a ton, especially with the test case — great job on making that code generic enough that it could be so easily repurposed @addaleax!
Fixes: https://github.com/joyeecheung/node-core-utils/issues/1
=> use ghauth for easier first-time auth flow

lib/links.js, lib/metadata_gen.js, test/unit/links.test.js, test/unit/metadata_gen.test.js
This fixes a very serious bug in parsing & creating Fixes URLs. Noticed it while landing: https://github.com/nodejs/node/commit/291ff72f859df3c4c3849021419f37cd542840a6
This should warrant a new release on npm since this makes `get-metadata` very problematic to use.
=> fix the parsing of fixes

.editorconfig
Now, editorconfig automatically inserts a final new line when saving a file.
Related to: https://github.com/joyeecheung/node-core-utils/pull/71/ and https://github.com/joyeecheung/node-core-utils/issues/76
=> editorconfig: set insert_final_newline to true

bin/metadata.js, lib/metadata_gen.js, test/unit/metadata_gen.test.js
Just small changes to do less manipulation of metadata inside the `get-metadata` target so that we don't need to duplicate this code in any other targets that use metadata.
Also simplified the meta array generation to use spread operators — just lets us keep that code a lot shorter and easier to read.
=> less processing of metadata in the bin target

lib/auth.js, test/fixtures/run-auth-error.js, test/fixtures/run-auth.js, test/unit/auth.test.js
Add test case to cover the error state of `getCredentials`. Also changed `auth` to use `os.EOL`.
Fixes: #36
=> improve coverage for auth

.npmignore, package-lock.json, package.json
This also removes .npmignore because the "files" array in package.json
has priority over this file.
Fixes: https://github.com/joyeecheung/node-core-utils/issues/90
=> add steps directory to npm package

lib/mergeable_state.js, lib/pr_checker.js, queries/PR.gql, test/fixtures/conflicting_pr.json, test/fixtures/data.js, test/unit/pr_checker.test.js
Question:
- Should we log something when `mergeable === 'UNKNOWN'`?
Please, review it, I don't know if I put all the things in the correct place.
Fixes:  https://github.com/joyeecheung/node-core-utils/issues/68
=> pr_checker: add warn about conflicts

lib/pr_checker.js, package-lock.json, queries/PRCommits.gql, test/fixtures/code_and_learn_pr.json, test/fixtures/commits_after_ci.json, test/fixtures/data.js, test/fixtures/more_than_three_commits_after_review_commits.json, test/fixtures/more_than_three_commits_after_review_reviews.json, test/fixtures/multiple_commits_after_review_commits.json, test/fixtures/reviews_approved.json, test/fixtures/single_commit_after_review_commits.json, test/unit/pr_checker.test.js
To keep noise level to minimum, only warn about last 3 commits since the last review.
Same exact work for `checkCI` is coming in next pr.
idea: we can also have flag for how much commits to log.
=> PRChecker: Update `commitsAfterReview` to warn only last 3 commits

README.md
It should still point to joyeecheung/node-core-utils until its implemented through github-bot
Refs: https://github.com/nodejs/node-core-utils/pull/100
=> Fix appveyor badge.

README.md, components/metadata.js, lib/args.js, lib/pr_checker.js, test/unit/args.test.js, test/unit/pr_checker.test.js
Added flag `warn-commits` that defaults to 3.  Documented the flag in readme.
=> PRChecker: add flag `--warn-commits`.

lib/pr_checker.js, test/unit/pr_checker.test.js
Now core has the label `fast-track` and a PR that uses that label so i think it is time to add support for new label that @joyeecheung  opened a issue for.
=> PRChecker: support new label fast-track

lib/pr_checker.js, test/fixtures/data.js, test/fixtures/first_timer_pr_with_private_email.json, test/unit/pr_checker.test.js
Refs: https://github.com/nodejs/node/pull/15489
=> pr_checker: ignore private emails

lib/queries/PR.gql
GitHub api will soon support `filesChanged` field. By soon i mean they already added it, just waiting for it to appear in changelog.
Refs: https://platform.github.community/t/feature-request-files-field-in-pullrequest/4041/3
=> PR.gql: add field changedFiles

lib/args.js, test/unit/args.test.js
The old code just displayed `[object Object]` instead of the actual argument.
=> Show actual value in error message

README.md, lib/auth.js, test/unit/auth.test.js
Check $XDG_CONFIG_HOME/ncurc first, and fall back to `~/.ncurc`. This is similar to what other tools like git do.
~If this is acceptable then I'll fix up the auth test.~ Fixed
=> lib: support XDG config spec

README.md, bin/ncu-config, lib/config.js, lib/file.js, package.json
Part of https://github.com/nodejs/node-core-utils/pull/106, but I think we could get this in first since it's a separate command.
=> config: implement ncu-config

README.md, bin/git-node, components/git/git-node-help, components/git/git-node-land, lib/cli.js, lib/landing_session.js, lib/queries/SearchIssue.gql, lib/request.js, lib/run.js, lib/session.js, package.json
This was https://github.com/nodejs/node-core-utils/pull/98 , opening a new PR because the repo has been transferred so I need to update the branch of my fork instead.
=> bin: custom git commands

components/metadata.js, lib/cli.js, lib/pr_checker.js, lib/pr_data.js, lib/pr_summary.js, lib/queries/User.gql, test/fixtures/closed_pr.json, test/fixtures/code_and_learn_pr.json, test/fixtures/first_timer_pr.json, test/fixtures/first_timer_pr_with_private_email.json, test/fixtures/merged_pr.json, test/fixtures/odd_commits.json, test/fixtures/semver_major_pr.json, test/fixtures/simple_commits.json, test/unit/cli.test.js, test/unit/pr_checker.test.js, test/unit/pr_data.test.js, test/unit/pr_summary.test.js
Also logs out the commits and the committers, and the first-timer status.
Fixes: https://github.com/nodejs/node-core-utils/issues/132
=> pr-summary: move the PR summary into a new file

lib/cli.js, lib/landing_session.js, lib/run.js
1. Fixes: https://github.com/nodejs/node-core-utils/issues/142 by prompting for `git am -3` when the normal `git am` fails
2. Improve the prompt: handle cancellation, put a `? ` in the beginning with a separator above the prompt.
3. Display the commits in reverse order (i.e. oldest first) and display the `Landed in xxx...yyy` for copy-pasting.
=> Handle git-am failure, improve prompt

lib/pr_data.js, lib/queries/PR.gql, lib/queries/User.gql, test/unit/pr_data.test.js
This eliminates the need of query the user data in a separate request <del>and the user would not have to grant user:email permission to the token anymore.</del> EDIT: nope, still need the permission.
Refs: https://github.com/nodejs/node-core-utils/issues/150#issuecomment-358972583
cc @cPhost
=> query: directly query user data in PR.gql

test/fixtures/log_stream.js
https://github.com/nodejs/node-core-utils/commit/9961256d9a89cf09b184686f563b9fa2aa7e2fff fixed a bug where the stream passed to `cli` will not actually get assigned to ora, which revealed another bug in the cli tests (not mocking all the methods called by ora). This patch fixes that.
(TBQH I think the cli tests are rather superfluous and are just testing what the dependencies already test..)
=> test: fix cli test on windows

bin/ncu-team, package.json
Hello all!
Sorry for being inactive the last few months.
`bin` folder was not being included with the `eslint .` command (I think because files aren't `.js`)
=> Add `bin` folder to linting

bin/get-metadata, components/git/git-node-help, components/git/git-node-metadata, docs/git-node.md
get-metadata felt sort of left out of the organization of the other tools since it existed before and imo it seemed better as part of git-node.
=> bin: deprecate get-metadata and add git-node-metadata

lib/pr_checker.js, lib/queries/PRCommits.gql, test/fixtures/data.js, test/fixtures/incorrect_git_config_commits.json, test/unit/pr_checker.test.js
Finally fixed this 😅!
This is what the documentation say about the use field in  author (`GitActor`):
> The GitHub user corresponding to the email field. Null if no such user exists.
@joyeecheung i added new method called `checkGitConfig` since we want the non author committed PR to be checked and logged out. I removed a step where we check if the `oddAuthor` is a collaborator because this method is only called is the author is a first timer. And i request login for `user` since it needs to request something.
=> Detect if PR author has incorrect git config.

lib/landing_session.js
This is just a double check so it emits warnings rather than doing anything. It doesn't parse `git+ssh` URLs since they are not valid URLs according to http://url.spec.whatwg.org/ .
=> git-node: warn on unexpected remote repository url

components/git/metadata.js
Fixes: https://github.com/nodejs/node-core-utils/issues/130
@joyeecheung @cPhost Please take a look. I hope this is what was needed to be done.
=> get-metadata: fail with a non-zero exit status

components/git/epilogue.js, components/git/land.js, docs/git-node.md, lib/landing_session.js, lib/session.js
It now refuses to run if
1. User has not configured upstream or branch - no more defaults.
2. User is not on the branch configured
3. User is on detached HEAD
Refs: https://github.com/nodejs/node/pull/18914
Fixes: https://github.com/nodejs/node-core-utils/issues/198
=> git-node: refuse to run without configurations/on wrong revs

lib/landing_session.js
It currently outputs a warning for SSH urls because WHATWG URL does not support that. Also does not trim the output from `git config` so there might be false warnings. This might create confusion to users who have SSH urls since we do not disencourage that in core.
Update to only check the owner and repo instead.
=> git-node: do not require https:// urls or github.com urls

components/git/land.js
When running `git node land --amend` from the command line, the HEAD is usually detached anyway (in the middle of a rebase), so there is no need to check the current branch.
=> git-node: don't check for wrong branch in --amend or --continue

bin/get-metadata, lib/cli.js
* On Windows the node executable needs to be explicitly invoked.
* Make sure the data property exists before trying to use it when
printing error output.
=> lib,src: fixes for Windows and error output

components/git/metadata.js
The `/files` at the end of URL is handled by `PR_RE` already, so this pr just removes hashes is passed as url.
=> metadata: remove file hashes from passed url

lib/landing_session.js
`getUpstreamHead` should return the last remote commit, no the one before it.
Fixes: https://github.com/nodejs/node-core-utils/issues/216
=> fix landed in message for multiple commits

lib/ncurc_path.js
`git-node` is currently broken if `XDG_CONFIG_HOME` is not set becauseit's a real `undefined` if it's not set in the environment (whereas in tests, where it's explicitly set undefined, it will be coerced to `'undefined'`).
=> lib: fix XDG_CONFIG_HOME not being set

lib/landing_session.js, lib/links.js, lib/pr_data.js, lib/request.js, package-lock.json, package.json, test/unit/cli.test.js, test/unit/pr_data.test.js
This commit replaces request with node-fetch and jsdom (which
depends on request) with cheerio to get rid of DEP0005 warnings
under `export NODE_PENDING_DEPRECATION=1`.
Also renames `request.promise` to `request.text` since that's
the only use case it has in the current code base
Also removes the tests on the spinners because changes in ora
would break it. We should not be testing the output of ora in
our own tests.
=> lib: make NODE_PENDING_DEPRECATION happy

components/git/land.js, components/git/metadata.js, lib/cli.js, lib/pr_data.js, lib/run.js, lib/session.js
Also fixes the status code handling in git-node.
Fixes: https://github.com/nodejs/node-core-utils/issues/212
=> git: support readme configuration

lib/pr_checker.js, test/fixtures/comments_with_lite_ci.json, test/fixtures/data.js, test/unit/pr_checker.test.js
Fixes: https://github.com/nodejs/node-core-utils/issues/225
=> pr_checker: consider LITE CI as a ci requirement

lib/cli.js, lib/collaborators.js, lib/pr_data.js, test/fixtures/test_cli.js, test/unit/collaborators.test.js, test/unit/pr_data.test.js
Put the readme request code into the helper so it
can be reused by other utilities.
=> lib: refactor collaborator getters

lib/team_info.js
when logging team data we currently include a dash between
the profile name / link and the account name. If the account
name is blank, we still include the dash. This patch changes
the behavior to remove the dash in cases that the name
is blank.
=> lib: don't print dash for users without names

lib/landing_session.js, lib/session.js
- Suggest to add `-x "git node land --amend"` which will put
`exec git node land --amend` on every picked commit.
- Suggest to add `--autosquash` if `fixup!` or `squash!` appears
in the commit messages, which will add fixup or squash actions
to corresponding commits if they match the autosquash rules.
Used this to land https://github.com/nodejs/node/pull/20121 . Worked pretty well.
=> git-node: suggest -x and --autosquash for git rebase

.eslintrc, components/git/land.js, components/git/metadata.js, lib/ci.js, lib/links.js, lib/pr_checker.js, test/fixtures/comments_with_ci.json, test/unit/ci.test.js, test/unit/links.test.js, test/unit/pr_checker.test.js
- Put the PR URL parsing logic in links.js and reuse it
- Differentiate PR and commit jobs in preparation for https://github.com/nodejs/node-core-utils/pull/161
- Updates a few CI link patterns
=> lib: clean up PR and CI url parsing logic

lib/update-v8/applyNodeChanges.js, lib/update-v8/majorUpdate.js, lib/update-v8/util.js
Ref: https://github.com/nodejs/node/pull/20304
=> git-node v8: remove eu-strip during major upgrades

bin/ncu-ci, docs/ncu-ci.md, lib/ci.js
- Refactor `runQueue` into a function
- Added `ncu-ci rate` to calculate the green rate in https://github.com/nodejs/reliability#ci-health-history. Example: https://github.com/nodejs/reliability/commit/dbd1790e6d3b033464f74174cbf9df070ba4c820
=> ncu-ci: add `ncu-ci rate`

lib/ci/ci_type_parser.js, test/fixtures/comments_with_ci.json, test/unit/ci_type_parser.test.js, test/unit/pr_checker.test.js
This helps newer CI runs take precedence over old ones if they
are posted in the same comment (usually done when someone
use `<del>` to delete a bad build in the comment
to avoid multiple notifications)
=> ci: parse CI links after sorting the comments by publishedDate

lib/ci/ci_failure_parser.js, lib/ci/ci_result_parser.js, test/fixtures/jenkins/git-failure-2/expected.json
New format is in https://github.com/nodejs/reliability/issues/14 Added a few more patterns and linkify the machine names as well as console of example stacks
=> ci: tweak patterns, improve markdown output

lib/ci/ci_failure_parser.js, lib/ci/ci_result_parser.js
Refs: https://github.com/nodejs/reliability/issues/17#issuecomment-424749959
Refs: https://github.com/nodejs/reliability/issues/18#issuecomment-426319812
=> ci: detect resume failures, tweak markdown output

lib/landing_session.js
The command final fails if am/rebase is in progress:
https://github.com/nodejs/node-core-utils/blob/c848152f6d19135e032fbf77b468780f64404f0e/lib/session.js#L184-L189
This PR adds a message to inform the user to complete exiting am/rebase before running final
=> git-node: message to do rebase/am before final

lib/cli.js, test/unit/cli.test.js
Also removes the formatting in CLI tests since there isn't too much point to test the exact output
=> cli: indent results, make warning and errors bold

lib/update-v8/backport.js, package-lock.json, package.json
Instead of performing `git apply` and aborting if it fails (which happens often), perform `patch -p1 --merge` instead to produce merge artifacts and then prompt for user input to continue.
It should look something like this:
=> git-node v8: prompt on merge conflict

package.json
Fixes this error:
```
PS D:\Documents\GitHub\nodejs\node-core-utils> npm run lint
> node-core-utils@1.16.0 lint D:\Documents\GitHub\nodejs\node-core-utils
> eslint . 'bin/*' --cache
Oops! Something went wrong! :(
ESLint: 5.9.0.
No files matching the pattern "'bin/*'" were found.
Please check for typing mistakes in the pattern.
```
=> package: fix lint script for Windows

lib/collaborators.js, lib/pr_checker.js, test/fixtures/data.js, test/unit/collaborators.test.js, test/unit/pr_checker.test.js
One Collaborator approval is enough only if the pull request
has been open for more than 7 days
Refs: https://github.com/nodejs/node/pull/22255
=> git-node: wait time for PR with single approval

README.md
When I copied these line into `.gitignore_global`, I found it didn't work well.
https://github.com/nodejs/node-core-utils#make-sure-your-credentials-wont-be-committed
```
.ncurc  # node-core-utils configuration file
.ncu    # node-core-utils working directory
```
Then I found these from stackoverflow.com:
https://stackoverflow.com/a/46477624/8102333
It seems that `.gitignore` wouldn't work if having inline comments, so I move comments to separate lines.
=> chore: fix invalid inline .gitignore

lib/session.js
Stray means to wander away from the right place or group, but upstream
commits are exactly where they should be, ready to be pulled. Use "new"
instead of "stray" to describe them.
=> session: don't call new upstream commits "stray"

package.json
It's not a big deal, because these "vulnerabilities" are only in dev deps, but might as well update.
There is another "vulnerability" in js-yaml is via mocha, https://github.com/nodejs/security-wg/issues/520, but it has to be fixed there because mocha is pinning its dependency's versions.
=> package: update nyc to 14.x

.mocharc.json, package.json
- Created `.mocharc.json` where current & future flags/options can be placed
- Removed the `exit` option.  Recommended practice is to only use `--exit` if a) your test process won't quit without it, and b) it's too difficult or time-consuming to fix your tests to cleanup properly.  Since the test process exits cleanly, I removed it.
=> test: create Mocha config file; remove unneeded "exit" option

lib/update-v8/updateVersionNumbers.js
yargs deceleration is
https://github.com/nodejs/node-core-utils/blob/db93b941c39afe012cfdf27508146b1662314ed3/components/git/v8.js#L26-L29
=> v8: fix use for --no-version-bump

components/git/v8.js, docs/git-node.md, lib/update-v8/updateVersionNumbers.js
Use abi_version_registry.json as a reference and update it.
/cc @refack @ryzokuken
=> v8: fix NODE_MODULE_VERSION bump

lib/landing_session.js
Change order to be slightly more consistent with previous message,
and so that the URL of the PR does not have to be followed directly
by a `:`. Some terminals consider the `:` to be part of the URL,
so clicking on it ends up on an invalid github page. Rearranging the
message so the URL is bounded by whitespace should work with all
terminals, and is no less readable.
=> lib: change order of "Post in" message

test/fixtures/README/README_alternative.md, test/fixtures/collaborators_alternative.json, test/fixtures/data.js, test/unit/collaborators.test.js
张三 is roughly the Chinese version of [John Doe](https://en.wikipedia.org/wiki/John_Doe) (modulo it is not used for corpses)
=> test: test collaborator names with parentheses

lib/landing_session.js
Makes it possible to land a commit that does not pass
the core-validate-commit checks in case there is a bug
in the validator.
=> git-node: add a prompt for force landing commits with invalid message

lib/ci/ci_result_parser.js
Previously we try to detect the type of the failed phase
and return a generic build failure when the job failed in a
non-test phase. This is not really necessary - the console
text parser is capable of detecting the actual build failure
from even the console text of the build phase. Also hard-coding
the test phase name makes the detection fragile when there
are configuration changes in the Jenkins. So we should just
skip the detection.
Fixes: https://github.com/nodejs/node-core-utils/issues/344
=> ncu-ci: parse console text of the first failed phase

bin/ncu-ci, lib/ci/ci_result_parser.js
- Refactor the ncu-ci command handling
- Display health statistics and a TODO list in the
`ncu-ci walk <type> --stats` output
See https://github.com/nodejs/reliability/issues/23 for an example.
=> ncu-ci: improve ncu-ci output

lib/ci/ci_type_parser.js, test/fixtures/commits_after_ci.json, test/unit/pr_checker.test.js
Fixes: https://github.com/nodejs/node-core-utils/issues/353
cc @sam-github
=> ci-parser: fix detection of lite CI pipelines

lib/team_info.js
It can't distinguish between the two, but I get sent on a roundabout
error hunt when ncu-team reported that it couldn't find the correct
line in my file, when actually the file name was misspelled and it
was trying to match against an empty string.
=> ncu-team: make sync report missing or empty files

docs/ncu-config.md
Fixed a typo when I read through this tool's documentations. Hope you don't mind. :)
=> Fixed a typo in ncu-config.md

lib/pr_checker.js, lib/queries/PR.gql, test/fixtures/closed_pr.json, test/fixtures/merged_pr.json, test/unit/pr_checker.test.js
To be consistent with PR `createAt` field, also reporting when the PR was closed or merged.
=> pr_checker: report when the PR was closed

lib/landing_session.js
Its not obvious to first-time users.
Personally, I'd prefer `git rebase upstream/master -i -x "git node land --amend" && git node land --continue` for ease of single-shot cut-n-paste, but maybe that's too unix specific?
=> git-node: mention --continue has to be done

bin/ncu-config, docs/ncu-config.md, lib/config.js
Project config file is intended to be committed to a project. This will
allow other projects in the org to use NCU without users having to set
`owner` and `repo` by themselves. In the future we can also use this add
other project-specific configurations (number of hours to wait, minimum
approvals and main CI, for example).
=> ncu-config: introduce project config file

lib/ci/ci_result_parser.js, lib/landing_session.js, lib/pr_checker.js, lib/session.js, lib/update-v8/backport.js, lib/utils.js, lib/wpt/index.js, test/unit/pr_checker.test.js
GitHub already refused to generate a link with 7.
=> fix: use 8 characters for commit SHAs

lib/update-v8/constants.js
Add zlib to the list of V8 dependencies, un-breaking LKGR.
=> update-v8: add zlib as a V8 dependency

docs/git-node.md, lib/pr_checker.js, lib/session.js, test/fixtures/data.js, test/unit/pr_checker.test.js
Add two new config options: `waitTimeSingleApproval` and
`waitTimeMultiApproval`, which can be used to set how long ncu should
wait before landing a PR with 1 approval or with 2+ approvals.
=> git-node: add config option to set wait times

lib/update-v8/constants.js
They are not needed to build V8 and cause issues with our release CI.
I'm intending to fix this issue:
=> v8: ignore zlib test and bench directories

components/git/land.js, docs/git-node.md, lib/cli.js, lib/landing_session.js, test/unit/cli.test.js
Non-interactive mode will try to land a Pull Request without asking any
questions. This is meant to be used by scripts and CI landing tools.
=> land: add non-interactive mode

lib/update-v8/constants.js
This is needed to fix the Node.js v8-canary builds.
Refs: https://chromium.googlesource.com/chromium/src/third_party/zlib/+/refs/heads/master/google/
=> v8: only ignore test in third_party/zlib/google

components/git/land.js, docs/git-node.md, lib/landing_session.js, lib/links.js, lib/metadata_gen.js, lib/session.js, test/fixtures/data.js, test/fixtures/pr_with_backport.json, test/unit/metadata_gen.test.js
This commit adds functionality to land that allows you to land backports
with the correct metadata
example: `git node land --backport <PR number>`
Co-authored-by: @AshCripps <ashley.cripps@ibm.com>
=> git-node: add --backport flag to land

lib/backport_session.js, lib/cli.js, lib/landing_session.js, test/unit/cli.test.js
Refs https://github.com/nodejs/node-core-utils/pull/388.
Extend `cli.prompt()` to allow for optional separators at the beginning of the prompt, as well as optional input types. This would allow for prompting input as is done in the above linked PR without adding a new function in the CLI class.
cc @joyeecheung
=> refactor: extend cli.prompt

lib/pr_checker.js, lib/queries/PRCommits.gql, lib/request.js, lib/session.js, test/fixtures/data.js, test/fixtures/github-ci/both-apis-failure.json, test/fixtures/github-ci/both-apis-success.json, test/fixtures/github-ci/check-suite-failure.json, test/fixtures/github-ci/check-suite-pending.json, test/fixtures/github-ci/check-suite-success.json, test/fixtures/github-ci/commit-status-only-failure.json, test/fixtures/github-ci/commit-status-only-pending.json, test/fixtures/github-ci/commit-status-only-success.json, test/fixtures/github-ci/no-status.json, test/fixtures/github-ci/status-failure-check-suite-succeed.json, test/fixtures/github-ci/status-succeed-check-suite-failure.json, test/fixtures/github-ci/two-commits-first-ci.json, test/fixtures/github-ci/two-commits-last-ci.json, test/unit/pr_checker.test.js
Some project in the org don't use Jenkins, which means PRChecker will
never succeed for pull requests on those projects. These projects
usually have Travis, AppVeyor or other CI systems in place, and those
systems will publish the status to GitHub, which can be retrieved via
API. This commit adds GitHub status as an optional way to validate if a
PR satisfies the CI requirement.
We need to check for the CI status in two fields returned by our GraphQL
query: commit.status for services using the old GitHub integration, and
commits.checkSuites for services using the new GitHub integration via
GitHub Apps.
=> git-node: add GitHub status as a CI option

CONTRIBUTING.md
"intergration" is a misspelling of "integration".
=> Fixing a typo in CONTRIBUTING.md

components/git/release.js, lib/prepare_release.js, lib/release.js, package.json
This PR constitutes the first portion of an automated release flow to abstract away the tedious aspects of preparing and promoting releases.
The preparation and promotion aspects of this new flow will be split into two separate PRs for easier review, so this is just the preparation step, with the promotion step marked as a TODO for implementation in a subsequent PR.
There are several things i'd like to refactor to make this a little less verbose in the future, but to avoid scope creep for now i've just marked some of them TODO and unless you all feel they are blocking i'll move to address them in follow-ups.
=> git-node: add git-node-release

docs/git-node.md
Add documentation for new command merged in https://github.com/nodejs/node-core-utils/pull/388.
cc @nodejs/releasers
=> docs: document git-node-release

lib/prepare_release.js
The generated release commit for LTS releases should contain the codename.
Previously, this was the auto-generated output for an LTS release commit:
```
2020-04-08, Version 10.20.0 (LTS)
```
when it should be:
```
2020-04-08, Version 10.20.0 'Dubnium' (LTS)
```
This fixes that issue.
cc @nodejs/releasers
=> fix: LTS release commit should contain codename

lib/prepare_release.js
- Prevent out of memory error because of infinitely growing array
- Do not quote LTS codename twice in changelog and commit message
- Add "PR-URL: TODO" to the release commit message
- Ask to push the proposal branch
=> git-node: fix release preparation script

lib/run.js
Refs https://github.com/nodejs/node-core-utils/pull/402#issuecomment-623726579.
Allow a non-empty `stderr` in `runSync` and instead error on a non-zero exit status; `git` sometimes outputs its messages to `stderr` so this has potential to cause unexpected failures.
cc @targos @joyeecheung
=> refactor: allow non-empty stderr in runSync

lib/prepare_release.js
Little fixup to the previous commit.
You really need to prepare an actual release to test this 😅
=> git-node: fix release preparation script (2)

lib/cli.js, test/unit/cli.test.js
Fixes an edge case whereby if the user prompted for a `number` or `input` type and did not provide a default answer, `prompt()` would return true and like created a weird state.
This fixes that by enforcing that if non-`confirmation` prompts are invoked, a default is enforced. Also added tests to confirm correct behavior.
cc @targos @joyeecheung
=> fix: enforce default for non-confirmation prompts

lib/prepare_release.js
Refs. https://github.com/nodejs/branch-diff/pull/22.
Leverages new `plaintext` functionality in `branch-diff` so that we can easily pull the notable changes into release commits without markdown cruft. New sample output:
```sh
build:
* add --error-on-warn configure flag (Daniel Bevenius) https://github.com/nodejs/node/pull/32685
cluster:
* fix error on worker disconnect/destroy (Santiago Gimeno) https://github.com/nodejs/node/pull/32793
crypto:
* check DiffieHellman p and g params (Ben Noordhuis) https://github.com/nodejs/node/pull/32739
* generator must be int32 in DiffieHellman() (Ben Noordhuis) https://github.com/nodejs/node/pull/32739
* key size must be int32 in DiffieHellman() (Ben Noordhuis) https://github.com/nodejs/node/pull/32739
```
cc @targos
=> fix: use plaintext formatting in release commit

components/git/wpt.js, docs/git-node.md, lib/wpt/index.js
Add an option to explicitly specify the commit the WPT subset
should be updated to instead of always using the latest commit.
=> git-node: implement --commit option of `git node wpt`

bin/ncu-ci
Closes https://github.com/nodejs/node-core-utils/issues/393.
Not a perfect solution, but this validates that the user didn't type something like:
```
ncu-ci --markdown url https://ci.nodejs.org/job/node-test-pull-request/29714/
```
and throws a helpful error if that's the case.
cc @mmarchini @joyeecheung
=> fix: validate ncu-ci args

lib/prepare_release.js
Non-confirmation inputs need to have a default date - if no date is provided for the release, default to today's.
cc @targos @joyeecheung
=> fix: default date for release

components/metadata.js, lib/ci/ci_type_parser.js, lib/pr_checker.js, test/unit/pr_checker.test.js
Closes https://github.com/nodejs/node-core-utils/issues/377.
We were previously checking for actual CI results in GitHub Actions-based CI, but not for Jenkins - this adds in and updates logic to aggregate Jenkins results into landing preparation.
Using https://github.com/nodejs/node/pull/33498 as a test case:
Before:
After:
cc @sam-github @joyeecheung @targos
=> feat: check CI failures before land

components/git/land.js, lib/session.js, lib/sync_session.js
Closes https://github.com/nodejs/node-core-utils/issues/423.
We were checking for missing config components after the Session was created, but the session ctor itself assumes those components will be present since it tries to use them to check the remote repo URL. This PR moves that check into the ctor itself for a better error experience:
cc @joyeecheung @targos
=> fix: check missing config in Session ctor

components/git/v8.js, lib/update-v8/backport.js
Closes https://github.com/nodejs/node-core-utils/issues/421.
Switches to `git apply` vs system `apply`, since the available options for system `apply` differ between systems.
cc @targos
=> fix: use git apply not system apply

lib/update-v8/commitUpdate.js, lib/update-v8/updateVersionNumbers.js
Refs https://github.com/nodejs/node-core-utils/pull/432.
Corrects usages of `ctx.execGitNode` to account for new signature.
cc @targos
=> fix: correct for new execGitNode syntax

lib/proxy.js, lib/request.js, package.json
=> feat: support system proxy

lib/file.js
Trying to run:
```
ncu-ci walk pr --stats=true --cache=true --markdown results.md
```
will fail with:
```
Error: ENOENT: no such file or directory, mkdir
at Object.mkdirSync (fs.js:940:3)
at exports.writeFile (C:\Users\ja\AppData\Local\nvs\node\14.1.0\x64\node_modules\node-core-utils\lib\file.js:19:8)
at WalkCommand.serialize (C:\Users\ja\AppData\Local\nvs\node\14.1.0\x64\node_modules\node-core-utils\bin\ncu-ci:229:9)
at main (C:\Users\ja\AppData\Local\nvs\node\14.1.0\x64\node_modules\node-core-utils\bin\ncu-ci:371:24)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5) {
errno: -4058,
syscall: 'mkdir',
code: 'ENOENT'
}
```
(at least on Windows).
This fixes this by first checking if there is any folder to create before calling `mkdir`.
=> fix: write file to the current folder

lib/deprecations.js, lib/landing_session.js, lib/prepare_release.js
Adds an additional step in `git node land` to automatically update any `DEP0XXX`, `DEP0XX1` etc tags in the codebase to incremented new numbers. The release preparation script will also check for unmarked numbers and optionally update them as well.
Tested locally but please double check for any potential edge cases i might have missed!
cc @targos
=> feat: handle unmarked DEP0XXX tags during landing and release

lib/prepare_release.js
We should also be excluding PRs with the `backport-open-vX.Yx` label from branch diffs.
cc @targos @BridgeAR
=> fix: also exclude backport-open label from branch diff

lib/landing_session.js
Closes https://github.com/nodejs/node-core-utils/issues/400.
Changes `downloadAndPatch()` such that whitespace issues aren't automatically fixed and a warning message is output to console instead (default behavior for the whitespace option of `git apply`)
cc @mmarchini @targos
=> fix: warn on whitespace during landing

lib/cli.js, lib/landing_session.js, lib/session.js
Adds an method to `cli` to set the process exit code, and use that
method on some known failure situations (missing config and `git node land`
failed checks). There are still more places where we should set exit
code.
Ref: https://github.com/nodejs/node-core-utils/issues/442
=> feat: set error code in some failure cases

components/git/land.js
--yes only worked with plain `git node land`, other options such as
--continue or --abort didn't accept --yes. Now it's possible to use
--yes with other options.
=> land: allow --yes to be used with other options

lib/prepare_release.js
Fixes a teeny spacing issue in `warnForWrongBranch()` when running release prep:
Before:
```sh
node on git:v14.x-staging ❯ g node release --prepare                           8:33PM
⚠  You are trying to create a new release proposal branch for v15, but you're checked out on v14.x-staging and not v15.x-staging.
ℹ  Switch to `v15.x-staging` with `gitcheckout v15.x-staging` before proceeding.
```
After: 
```sh
node on git:v14.x-staging ❯ g node release --prepare                           8:34PM
⚠  You are trying to create a new release proposal branch for v15, but you're checked out on v14.x-staging and not v15.x-staging. …
```
=> fix: spacing in warnForWrongBranch()

lib/landing_session.js
`--abort` shouldn't exit with error status code unless something goes
wrong.
=> land: fix --abort exit status code

lib/ci/ci_result_parser.js
Closes https://github.com/nodejs/node-core-utils/issues/452.
Fixes the following error:
```
------------------------------ Generated metadata ------------------------------
PR-URL: 
Backport-PR-URL: https://github.com/nodejs/node/pull/33126
Refs: https://github.com/nodejs/node/pull/32763
ℹ  Last Full PR CI on 2020-04-28T15:56:53Z: https://ci.nodejs.org/job/node-test-pull-request/31061/
⚠  Commits were pushed after the last Full PR CI run:
⚠  - stream: runtime deprecate Transform._transformState
✔  Build data downloaded
{
servlet: 'Stapler',
message: 'Not Found',
url: '/job/node-test-pull-request/31061/api/json',
status: '404'
}
TypeError: Cannot read property 'find' of undefined
at PRBuild.setBuildData …
```
=> fix: landing when no Jenkins CI has been run for PR

lib/landing_session.js, lib/session.js
node-core-utils is also used on other repositories across the Node.js
Org where deprecations are not logged into a file. Making it opt-out
allows node-core-utils to still be used on those repositories.
=> land: optional deprecations update

lib/run.js
This is extremely useful for debugging when stderr is empty.
@Trott @BethGriggs
=> fix: print full command in case of failure

lib/prepare_release.js
Changelogs were previously grouped but Notable Changes should be as well.
cc @MylesBorins
=> git-node: group notable changes during release prep

bin/ncu-ci, lib/ci/ci_result_parser.js, lib/ci/ci_type_parser.js
@sam-github heres my draft for what I have so far.
=> Add functionality for daily-master to NCU-CI

docs/ncu-ci.md
Refs https://github.com/nodejs/node-core-utils/pull/379.
Adds documentation for new command `ncu-ci daily`.
cc @mmarchini @joyeecheung @targos
=> docs: add docs for ncu-ci daily

bin/ncu-ci, lib/ci/ci_result_parser.js
Refs https://github.com/nodejs/node-core-utils/pull/379.
Fixes the following error:
```
node-core-utils on git:fix-set-daily-build-data ❯ ncu-ci daily                 11:55AM✔  Done--------------------------------------------------------------------------------
[1/16] Running health
| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2020-07-20 18:55 | 0       | 6       | 5        | 1       | 34      | 13.33%     |
[2/16] Running https://ci.nodejs.org/job/node-daily-master/2004/ …
```
=> fix: ensure node-test-commit job id in daily-master

lib/ci/ci_failure_parser.js
Some errors we see are caused by underlying infrastructure issues (most
commonly filesystem corruption). Correctly classifying can help when
collecting statistics, when pinging the build team, or even for
automated notification (see
https://github.com/nodejs/build/issues/2359).
=> ncu-ci: create INFRA_FAILURES category

lib/update-v8/constants.js, lib/update-v8/majorUpdate.js
Closes https://github.com/nodejs/node-v8/issues/166.
It appears that the latest version of V8 has stripped the `v8/` prefix out of pathing, so e.g in DEPS:
```js
'v8/build':
Var('chromium_url') + '/chromium/src/build.git' + '@' + '1b904cc30093c25d5fd48389bd58e3f7409bcf80',
'v8/third_party/depot_tools':
Var('chromium_url') + '/chromium/tools/depot_tools.git' + '@' + '454f4ba4b3a69feb03c73f93d789062033433b4c',
'v8/third_party/icu':
Var('chromium_url') + '/chromium/deps/icu.git' + '@' + 'f2223961702f00a8833874b0560d615a2cc42738',
'v8/third_party/instrumented_libraries':
Var('chromium_url') + '/chromium/src/third_party/instrumented_libraries.git' + '@' + 'bb3f1802c237dd19105dd0f7919f99e536a39d10',
'v8/buildtools':
Var('chromium_url') + '/chromium/src/buildtools.git' + '@' + …
```
=> fix: repo/path mismatch in v8 update

lib/update-v8/backport.js, lib/update-v8/commitUpdate.js, lib/update-v8/majorUpdate.js, lib/update-v8/minorUpdate.js, lib/update-v8/updateVersionNumbers.js, lib/update-v8/util.js
V8 versions < 8.6 do not specify a relative path in the DEPS file.
Fixes: https://github.com/nodejs/node-v8/issues/166
Refs: https://github.com/v8/v8/commit/56bf834a2b122616d00c6cc85243e4d80a1ca241
Refs: https://github.com/nodejs/node-core-utils/commit/57b7df8016a3d1495be4f67fc3cc34db21a2b3a6
I tested the code with `--branch=8.5-lkgr` and `--branch=lkgr` (8.6/master)
=> fix(v8): support non-relative paths in V8 DEPS

lib/ci/ci_type_parser.js, lib/pr_checker.js, test/fixtures/comments_with_ci.json, test/fixtures/comments_with_lite_ci.json, test/fixtures/commits_after_ci.json, test/fixtures/data.js, test/unit/ci_type_parser.test.js, test/unit/pr_checker.test.js
Lite CI is not used anymore, but some PRs got Lite-CI runs after some
changes to the bot. node-core-utils Lite-CI parsing is not working
though, therefore ncu will fail to land those PRs. Removing Lite-CI
checks fix the issue and also reduces complexity.
Fix: https://github.com/nodejs/node-core-utils/issues/466
=> chore(land): remove lite-ci checks

components/git/land.js, components/metadata.js, docs/git-node.md, lib/metadata_gen.js, test/unit/metadata_gen.test.js
Closes https://github.com/nodejs/node-core-utils/issues/470.
Allows for a collaborator to skip `Fixes: ` and `Refs: ` being automatically added to generated commit metadata if `--skipRefs` is passed.
=> fix: allow opt-out of Fixes/Refs metadata

lib/landing_session.js
Closes https://github.com/nodejs/node-core-utils/issues/427.
Runs `make lint` after the patch has been downloaded and applied, and optionally stage and amend updated files if lint fails.
=> fix: lint during the landing process

lib/links.js, lib/metadata_gen.js, test/fixtures/data.js, test/fixtures/pr_with_duplicate_refs.json, test/fixtures/pr_with_self_ref.json, test/unit/metadata_gen.test.js
Closes https://github.com/nodejs/node-core-utils/issues/350.
Closes https://github.com/nodejs/node-core-utils/issues/133.
Handles two potential edge cases:
* Duplicate `Refs: ` and `Fixes: ` items
* A ref to one's own PR.
=> fix(land): prevent duplicate and self-refs

lib/landing_session.js
Fixes an issue where `make lint` doesn't return anything, so `await`ing it would always return `undefined` on success and false-positive fail. Also adds logging output for successful lint.
cc @nodejs/node-core-utils
=> fix: return value for validateLint

components/git/land.js, lib/landing_session.js
This basically adds `--autorebase` that will run interactive rebase with `--autosquash` option to handle `!fixup` commits (but refuse to land `squash!` as those require msg editing) and `git-node land --amend` for each commit.
Hopefully this will allow us to land PRs with multiple commits in `commit-queue`.
Couldn't find a way to write tests for landing, did I miss it somewhere?
Also, anyone knows a better way to run `git-land` without the need for `shell: true` option?
/cc @nodejs/node-core-utils
=> feat: implement autorebase for PRs with multiple commits

components/git/land.js, lib/landing_session.js
Disable lint check by default and make it opt-in, so it doesn't impact
the workflow for collaborators, while providing a way for early birds to
try it out so we can tweak it until it works great for everyone (at
which point we can re-enable it by default).
Ref: https://github.com/nodejs/node-core-utils/issues/484
=> feat: make lint check opt-in

lib/ci/ci_type_parser.js, lib/pr_checker.js, lib/queries/PR.gql, lib/session.js, test/fixtures/comments_with_failed_ci.json, test/fixtures/comments_with_pending_ci.json, test/fixtures/comments_with_success_ci.json, test/fixtures/data.js, test/fixtures/jenkins/pending/node-test-pull-request-32777.json, test/fixtures/pull_requests/doc-only.json, test/unit/pr_checker.test.js
Doc-only changes don't need a full Jenkins CI, instead we can check
if the last Actions run was successful. Therefore this commit also adds
check for Action runs. Jenkins CI messages were improved as well.
Fix: https://github.com/nodejs/node-core-utils/issues/324
Ref: https://github.com/nodejs/node/issues/32335
=> feat: check Actions and handle doc-only changes

bin/ncu-ci, lib/ci/build-types/citgm_build.js, lib/ci/build-types/citgm_comparison_build.js, lib/ci/build-types/test_build.js
Improve handling for CITGM runs in `ncu-ci`.
Before:
```console
node on git:master ❯ ncu-ci citgm 2400                                8:59PM
[1/1] Running CITGM: 2400
⠙ Querying API for job/citgm-smoker/2400/----------------------------------- Summary ------------------------------------
Result     PENDING
URL        https://ci.nodejs.org/job/citgm-smoker/2400/
Source     
Commit     Unknown
Date       
Author     Unknown
TypeError: Cannot read property 'statistics' of undefined
at CITGMBuild.displayBuilds (/Users/codebytere/Developer/node-core-utils/lib/ci/build-types/citgm_build.js:115:56)
at CITGMBuild.display …
```
=> fix: handle citgm failures better

lib/landing_session.js, lib/run.js, lib/session.js
Working with patch files is, on the one hand, unclean because it
requires manual parsing to figure out e.g. the commit message subjects,
and on the other hand, poses actual problems when dealing with binary
files.
Clean the code up by fetching the original commits themselves and
applying those commits directly.
This also resolves some TODO comments, e.g. we can now check whether
the commits that are to be applied match the ones reported through
the GitHub API.
---
I’m not sure what kind of testing this patch needs? I’ve tried it out manually on one PR so far, but there doesn’t appear to be anything automated in place here.
=> chore(git-node): avoid dealing with patch files for landing

components/git/land.js, components/git/metadata.js, components/metadata.js
Closes https://github.com/nodejs/node-core-utils/issues/499.
Fixes incorrect arguments being passed to `getMetadata` and also updates export/import to be more in line with other components.
cc @nodejs/node-core-utils
=> fix: git node metadata arg passing

README.md, bin/get-metadata, bin/git-node, bin/ncu-ci, bin/ncu-config, bin/ncu-team, lib/request.js, lib/run.js, lib/verbosity.js
Support NCU_VERBOSITY=debug which tells ncu to log CLI commands
and HTTP requests to the command line for debugging.
Refs: https://github.com/nodejs/node-core-utils/issues/467
I switched to using environment variables instead of options since it's easier to turn the setting on/off that way. Also I left out `Pipe stdout and stderr, also do not use spinners if verbosity is on in case the output is overwritten` mentioned in https://github.com/nodejs/node-core-utils/issues/467 in this PR since that requires a bit more refactoring.
cc @nodejs/node-core-utils
=> feat: support NCU_VERBOSITY=debug environment variable

docs/git-node.md
Maybe it's worth mentioning when onboarding collaborators living in mainland China :)
=> docs: add a tip about using git-node-land behind firewall

.github/workflows/release-please.yml
The nature of the breaking changes is explained here: https://github.com/googleapis/release-please/pull/536
Closes: #508
=> chore: update release-please-action to v2.5.5

bin/ncu-ci, lib/ci/failure_aggregator.js
Closes https://github.com/nodejs/node-core-utils/issues/496.
Fixes two things: 
- `FAILURE_TYPES_NAME` should be imported from `CIFailureParser`
- `this.json` should be set regardless of whether the user has chosen to pass `--json`
cc @mmarchini
=> fix: undefined failures & JSON error

lib/update-v8/util.js
Actually include patch number in the version string when there is a
patch number.
=> fix(v8): correct order of ternary

components/git/release.js, docs/git-node.md, lib/prepare_release.js, lib/release/utils.js, test/fixtures/release/expected-test-process-release.js, test/fixtures/release/original-test-process-release.js, test/unit/prepare_release.test.js
Add an option to `git node release` that marks the release being
created as the transition from Current to LTS.
cc @nodejs/releasers
=> feat: automate creation of the first LTS release

.gitattributes, .github/workflows/nodejs.yml
Use a gitattributes file to force text files to be checked out with LF
line endings. This resolves issues on Windows with tests that compare
values with the contents of files on disk.
=> chore: fix tests on Windows and enable it in actions

lib/prepare_release.js
Fixes the following potential error:
```
Error: git config,--get,remote.undefined.url failed with stderr:
at exports.runSync (/Users/mylesborins/.nvm/versions/node/v14.15.0/lib/node_modules/node-core-utils/lib/run.js:84:11)
at new ReleasePreparation (/Users/mylesborins/.nvm/versions/node/v14.15.0/lib/node_modules/node-core-utils/lib/prepare_release.js:50:26)
at main (/Users/mylesborins/.nvm/versions/node/v14.15.0/lib/node_modules/node-core-utils/components/git/release.js:71:18)
at release (/Users/mylesborins/.nvm/versions/node/v14.15.0/lib/node_modules/node-core-utils/components/git/release.js:53:21)
at Object.handler (/Users/mylesborins/.nvm/versions/node/v14.15.0/lib/node_modules/node-core-utils/components/git/release.js:38:12)
at Object.runCommand …
```
=> fix: throw on missing info during release prep

lib/queries/PRCommits.gql
Closes https://github.com/nodejs/node-core-utils/issues/477.
Swaps `first` to `last` in `PRCommits.gql`
cc @mmarchini @targos
=> fix: fetch most recent 100 commits

README.md
Fixes: https://github.com/nodejs/node-core-utils/issues/525
=> doc: add documentation about setting up Jenkins credentials

lib/collaborators.js, test/fixtures/README/README.md
Because of changes to the README, node-core-utils `git node land` is now
broken. This fixes it. Please fast-track?
=> fix: accommodate case changes in README header

lib/github/tree.js, lib/request.js, lib/wpt/index.js
There are binary files in the WPT repository and downloading them as
text corrupts them.
Refs: nodejs/node#37294
=> fix(wpt): download files as buffer instead of text

lib/pr_checker.js, test/fixtures/first_timer_pr.json, test/unit/pr_checker.test.js, test/unit/pr_summary.test.js
Refs: https://github.com/nodejs/node/pull/37308
=> feat: update CI requirements for landing pull requests

lib/update-v8/majorUpdate.js
Add all V8 files with --force before updating DEPS. We have to do this
because some files are checked in by V8 despite .gitignore rules.
=> fix(update-v8): force-add all files after cloning V8

lib/cli.js
When `text` is longer than 78 characters (with default `length`), `rest` is negative, which raises an error at `repeat`, making some commands unusable (when a long argument is given).
```
RangeError: Invalid count value
at String.repeat (<anonymous>)
at CLI.separator (C:\Users\me\AppData\Local\Volta\tools\image\packages\node-core-utils\node_modules\node-core-utils\lib\cli.js:133:22)
at WPTUpdater.checkNeedsUpdate (C:\Users\me\AppData\Local\Volta\tools\image\packages\node-core-utils\node_modules\node-core-utils\lib\wpt\index.js:127:14)
at WPTUpdater.update (C:\Users\me\AppData\Local\Volta\tools\image\packages\node-core-utils\node_modules\node-core-utils\lib\wpt\index.js:155:36)
at main (C:\Users\me\AppData\Local\Volta\tools\image\packages\node-core-utils\node_modules\node-core-utils\compone …
```
=> fix(cli-separator): negative value on a long text

lib/update-v8/majorUpdate.js
It became the default recently.
Refs: https://chromium.googlesource.com/v8/v8.git/
=> fix(v8): use V8's main branch

.github/workflows/nodejs.yml
- chore(ci): test on supported Node.js versions
BREAKING CHANGE: Removed support for Node.js 10 and 15.
- chore(ci): update codecov-action to v2
=> Update CI workflows

.eslintrc, lib/collaborators.js, test/fixtures/README/README.md
This accommodates both the current README format and the upcoming README
format.
Refs: https://github.com/nodejs/node/pull/40137
=> feat: prepare ncu for new README format

lib/update-v8/constants.js, lib/update-v8/majorUpdate.js
Add new V8 dependency introduced in V8 9.6.
Refs: https://github.com/nodejs/node-v8/issues/211
cc @targos @nodejs/v8-update
=> update-v8: add abseil-cpp as a V8 dependency

lib/update-v8/constants.js
It was removed upstream because of issues with GCC.
=> fix(update-v8): remove abseil-cpp from V8 dependencies

lib/collaborators.js, test/fixtures/README/README.md
Using remark to format markdown files is going to require one final
README.md format change. This accommodates that change while being
backward-compatible with previous formats.
=> fix: prepare for one last README change

lib/pr_checker.js
Refs: https://github.com/nodejs/node-auto-test/pull/40#issuecomment-955670657
=> fix: display the correct amount of remaining time for fast-tracked PRs

.github/workflows/nodejs.yml
- Use latest LTS for lint job
- Add version 17.x to test matrix
=> chore: update Node.js in CI workflows

lib/update-v8/applyNodeChanges.js, lib/update-v8/backport.js, lib/update-v8/index.js, lib/update-v8/majorUpdate.js, lib/update-v8/minorUpdate.js, lib/update-v8/updateV8Clone.js, lib/update-v8/updateVersionNumbers.js, package.json
Replaces listr with listr2 and updates mocha. `npm install` no longer
reports audit issues on install.
I am not confident about the listr changes, especially replacing the use of listr-input with inquirer. Unfortunately, those are all in the v8-update code and it does not seem to be covered by tests. Perhaps @targos can test it?
=> chore: resolve all npm install warnings

components/git/land.js, lib/landing_session.js, lib/queries/DefaultBranchRef.gql
Fail if the user is trying to land a commit on "master" or "main", and
the default branch name doesn't match.
=> feat(land): avoid landing on the wrong default branch

lib/prepare_release.js
Upstream changes to the Node.js `CHANGELOG.md` no longer escape `_`
characters in markdown links.
Refs: https://github.com/nodejs/node/pull/40645
Refs: https://github.com/nodejs/node-core-utils/pull/575#issuecomment-952262877
---
Hopefully the churn has settled down now 🤞.
=> fix: update detection of changelog links

lib/request.js, package.json
Closes https://github.com/nodejs/node-core-utils/issues/594.
=> fix(deps): revert to node-fetch

lib/landing_session.js
When running `git node land <pr> --autorebase --fixupAll`, ncu should squash all the commits first, then ignore the `--autorebase` flag as there is only one commit left.
This comes up in the CQ for nodejs/node repo, we could fix the CQ script so it only supply one flag or the other, but since I didn't find any documentation stating the `--fixupAll` is ignored when using `--autorebase`, I thought it would be worth fixing it.
Refs: https://github.com/nodejs/node/pull/40696#issuecomment-967642528
=> fix: fixupAll flag should take precedence over autorebase

lib/pr_checker.js, lib/queries/PRCommits.gql, test/fixtures/github-ci/success-dependabot-queued.json, test/unit/pr_checker.test.js
```
fix: fetch first 100 check suites in PR checker
10 is not enough, as we have around 25 GitHub checks nowadays.
```
```
fix: allow pending dependabot checks in PR checker
GitHub support says that they are expected to show up by design.
This also removes some code duplication and normalizes log level and format.
```
=> Fix PR checker for GitHub Actions CI

lib/team_info.js, test/fixtures/ncu_team_sync_expected.md, test/fixtures/ncu_team_sync_out.md, test/unit/team_info.test.js
The markdown style linting for our repos requires `*` instead of `-` for
unordered lists. Because ncu-team uses `-`, it results in failing lints
in some repos, thus requiring manual changes to the output. Use `*`
instead so that becomes unnecessary.
I had this problem in https://github.com/nodejs/TSC/pull/1189.
Refs: https://github.com/nodejs/TSC/commit/3cbcd5a02c400d7c0886683166f9ff320c2c0f5c
=> fix: comply with markdown style guidelines

lib/auth.js, test/unit/auth.test.js
The current username and token validation regular expressions will match
any string. This adds tests and fixes the regular expressions.
=> fix: correct username and token validation

package.json
mocha defaults to a 2000ms timeout, which frequently causes CI to fail.
Since such short timeouts are pretty much useless, vastly increase the
timeout to one minute per test.
=> chore: increase test timeouts to avoid flaky tests

lib/file.js
Pretty-printed JSON files should end with `\n`.
=> fix: add trailing line feed to formatted JSON

lib/request.js
Without this, when using `git node wpt`:
```console
tniessen@ubuntuserver:~/dev/node$ node ../node-core-utils/bin/git-node.js wpt wasm/webapi
⚠  Please create wasm/webapi.json in test/wpt/status
--------------------- Checking updates for wasm/webapi... ----------------------
Last local update for wasm/webapi is fd1b23eeaaf9
✔  wasm/webapi is up to date with upstream (fd1b23eeaaf9)
⠸ Updating license...(node:596531) [node-fetch#buffer] DeprecationWarning: Please use 'response.arrayBuffer()' instead of 'response.buffer()'
(Use `node --trace-deprecation ...` to show where the warning was created)
✔  Updated test/fixtures/wpt/LICENSE.md.
```
Tracing it:
```console
tniessen@ubuntuserver:~/dev/node$ node --trace-deprecation ../node-core-utils/bin/git-node.js wpt wasm/webapi
⚠  Please create …
```
=> fix: use res.arrayBuffer() instead of res.buffer()

lib/config.js
Before:
```
undefined:5
}
^
SyntaxError: Unexpected token } in JSON at position 138
at JSON.parse (<anonymous>)
at exports.readJson (…/lib/file.js:38:17)
at Object.exports.getConfig (…/lib/config.js:34:10)
at Object.exports.getMergedConfig (…/lib/config.js:26:32)
at Object.<anonymous> (…/components/git/metadata.js:8:44)
at Module._compile (node:internal/modules/cjs/loader:1097:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
at Module.load (node:internal/modules/cjs/loader:975:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:999:19)
Node.js v17.6.0
```
After:
```
…/lib/config.js:39
throw err
^
Error: Unable to parse config file /home/~/.ncurc
at Object.exports.getConfig …
```
=> config: add file path to error message when parsing fails

lib/pr_checker.js, test/fixtures/comments_with_two_fast_track.json, test/fixtures/data.js, test/unit/pr_checker.test.js
Refs: https://github.com/nodejs/node/pull/42141
=> fix: check last fast-track request comment

lib/cli.js
• List the available types by a `ListFormat` formatter.
• Replace unnecessary conditional check.
• Use switch statement for better readablity and performance.
• Avoid casting strings to strings.
=> refactor(cli): apply optimizations

.github/workflows/nodejs.yml, package.json
- chore(ci): test on supported Node.js versions
BREAKING CHANGE: Removed support for Node.js 12 and 17.
- chore: update some dependencies
=> Update tested Node.js versions and mocha

lib/ci/ci_failure_parser.js, test/fixtures/jenkins/test-runner-test-failure/expected.json, test/unit/ci_failure_parser.test.js
fix https://github.com/nodejs/node-core-utils/issues/639
=> fix: parse ci failure error

lib/landing_session.js
Use `git interpret-trailers` (probably requires a fairly recent git version) to see if the original commit message already contains trailers and do not add an empty line before adding metadata if it does (as suggested in https://github.com/nodejs/node-core-utils/issues/602#issuecomment-1015172790). This should fix how `git node land` treats `Co-authored-by` lines.
No reordering happens. The generated metadata is appended to the existing trailer. My understanding is that the order of trailers is irrelevant, but if that's not true, we might want to revisit that part.
This particular part of the code base does not seem to be covered by any tests, so please review carefully.
Fixes: https://github.com/nodejs/node-core-utils/issues/602
=> fix: respect existing trailers in commit messages

lib/landing_session.js
We can detect when we're running from a GitHub Actions runner, and output an error message specific to the CQ (as `Use --fixupAll` is not a very actionable workaround in the context of the CQ).
=> fix: add a specific error message for the commit queue

bin/ncu-ci.js, lib/ci/ci_utils.js
This excludes CI runs prior to a certain date, which can be useful when trying to know the status of the CI after a flake is fixed.
=> feat: add --since option to ncu-ci

lib/backport_session.js
Previously we parse the entire commit, including the diff, which can result in ENOBUFS errors. Adding `-s` option to the `git show` command would eliminate the commit body in the output, which we don't need, so the error can be less likely to happen during commit message analysis.
=> fix: only parse commit messages during git node backport analysis

.npmrc, lib/ci/run_ci.js, test/unit/ci_start.test.js
fix: https://github.com/nodejs/node-core-utils/issues/559
test pr: https://github.com/nodejs/node/pull/44986
Hopefully this will make us test v8 easier :)
local test
```
node bin/ncu-ci.js run 44986
```
currently I run into Jenkins credentials invalid. But I have used this credential before, and it worked.
cc @targos @richardlau @nodejs/v8-update
=> feat: add auto run v8 ci

bin/ncu-ci.js
This should fix the (additional) issue mentioned in https://github.com/nodejs/node-core-utils/issues/653#issuecomment-1293687908
=> fix: add missing await

components/git/release.js, docs/git-node.md
I reach to `node-core-utils` for automating the LTS release commit but I couldn't get it to work due to the lack of a proper usage example.
I'm adding examples to both the markdown docs and the cli help output which are the places I would have loved to have found these.
```
$ git node release --help
git-node release [newVersion|options]
Manage an in-progress release or start a new one.
Positionals:
newVersion, options  Version number of the release to be prepared or promoted
Options:
--version   Show version number                                      [boolean]
--help      Show help                                                [boolean]
--prepare   Prepare a new release of Node.js                         [boolean]
--promote   Promote new release of Node.js …
```
=> doc: add startLTS usage examples

README.md, docs/ncu-ci.md
The [Make sure your credentials won't be committed](https://github.com/nodejs/node-core-utils#make-sure-your-credentials-wont-be-committed) part of guide implies that `~/.gitignore_global` is a default path for global gitignore.
If anyone followed this part too literally, I'd recommend to doublecheck their setup with something like:
```bash
$ cat "$(git config --global core.excludesFile || echo ${XDG_CONFIG_HOME:-${HOME}/.config}/git/ignore)"
```
This is applicable to Linux; I'm unsure about other platforms.
`git config --global core.excludesfile` should work everywhere, but note that setting it overrides file in default location (if any).
=> docs: clarify global gitignore and fix typos

lib/update-v8/constants.js
This change add ittapi to the V8 dependency list. The ittapi library is used in V8 to profile JIT-compiled JavaScript code and support instrumentation for JavaScript code.
Refs: https://github.com/nodejs/node/pull/39374
=> v8: add ittapi as V8 dependency

lib/cli.js, package.json, test/unit/ci_start.test.js, test/unit/cli.test.js
Fixes the annoying bug, when a question is asked through the client and a spinner is already taken place. This pull request, pauses and restarts the spinner after the answer.
Example:
=> cli: handle spinning states

.github/workflows/nodejs.yml, lib/request.js, package.json
Fixes #626
When updating WPT resources, the `wpt` command would sometimes throw a `ERR_STREAM_PREMATURE_CLOSE` error. Switching to `undici` fixes this issue.
The `undici` `fetch` function is only supported on Node 16+. After discussing with the team, we agreed that dropping support for Node 14 in this tool was acceptable (https://github.com/nodejs/node-core-utils/issues/626#issuecomment-1433053922).
```
➜  node git:(main) ✗ ./node /Users/austinkelleher/Documents/open-source/node-core-utils/bin/git-node.js wpt resources
---------------------- Checking updates for resources... -----------------------
Last local update for resources is fbf1e7d24776
✔  Last update in upstream is 66933c819b6e
✔  Read asset list, 165 files in total.
Excluded 133 files, 32 files to write.
--------------- Writing …
```
=> fix: switch to undici for requests to fix stream close errors

lib/pr_checker.js, test/fixtures/pull_requests/code-change.json, test/fixtures/pull_requests/doc-only-in-tools.json, test/unit/pr_checker.test.js
This pr ignores .md files when do `requiresJenkinsRun` check
Refs: https://github.com/nodejs/node/pull/43483#issuecomment-1160210710
cc @aduh95
=> feat: ignore .md files when do `requiresJenkinsRun` check

lib/landing_session.js
I had to manually change the commit message in one PR, and totally forgot to continue the landing process with `git node land --continue` this may be helpful for new collaborators.
=> git-node: improve instructions logs when manual amending is required

README.md
The Node.js Jenkins server now only allows you to access your Jenkins profile with your GitHub username rather than your GitHub ID.
=> docs: update Jenkins profile access

lib/links.js, package.json
Cheerio has deprecated the default export, instead we should be using the named ones.
=> chore(deps): do not use the deprecated Cheerio API

CONTRIBUTING.md, README.md, docs/ncu-ci.md
Ref: https://github.com/nodejs/node-core-utils/pull/668#discussion_r1118120661
=> docs: fix indentation to comply with CommonMark

lib/update-v8/majorUpdate.js
Sometimes there might be additional tags with suffix such as `-pgo`
=> fix: use correct V8 tag for major updates

lib/pr_checker.js, test/unit/pr_checker.test.js
If a PR has `fast-track` with not enough approvals, instead of exiting with error we can proceed to see if it meets regular time requirements.
This also makes error more informative, showing these requirements.
=> fix: treat `fast-track` with not enough approvals as non-fatal

lib/file.js, lib/wpt/index.js
Removes the updated directory before pulling fresh assets.
closes #678
=> fix(wpt): remove stale fixtures before pulling fresh ones

lib/landing_session.js
I personally find it useful to keep the cherry-pick session as is to help with debugging what's going wrong.
=> fix: do not run `git cherry-pick --abort` on failure

package.json
Without it, I'm unable to run the linter locally.
=> chore(deps): replace `eslint-plugin-node` with `eslint-plugin-n`

lib/landing_session.js
Fixes: https://github.com/nodejs/node-core-utils/issues/619
=> feat(git-node): allow empty commits with fixupAll

lib/pr_checker.js, lib/queries/Reviews.gql, test/fixtures/more_than_three_commits_after_review_reviews.json, test/fixtures/multiple_commits_after_review_reviews.json, test/fixtures/reviews_approved.json, test/fixtures/reviews_requesting_changes.json, test/fixtures/single_commit_after_review_reviews.json, test/unit/pr_checker.test.js
Before this commit, any review after the last commit would disable the warning and let the CQ land the PR. This commit makes sure that only approving reviews from collaborators are taken into account to decide if a PR is ready to land.
Refs: https://github.com/nodejs/node-core-utils/issues/677#issuecomment-1454263877
Fixes: #643
=> fix(pr_checker): do not count non-approving reviews

.eslintrc, components/git/land.js, lib/landing_session.js
I've also extended the max line length from 80 to 100 as it was making less readable to keep it at 80 IMO.
=> feat(git-node): add support for the `--gpg-sign` git flag

package.json
- Update the `core-validate-commit` dependency to the next major version (https://github.com/nodejs/core-validate-commit/commit/8cf9e8602ff7894cad92e5a16a16961aad4e071d is the only change in this release).
- Update all other dependencies and developer dependencies to their latest versions.
=> chore: update core-validate-commit and others

lib/update-v8/index.js, lib/update-v8/updateMaintainingDependencies.js, lib/update-v8/updateVersionNumbers.js
Update `doc/contributing/maintaining/maintaining-dependencies.md` on major V8 updates. Marked as draft in order to wait for https://github.com/nodejs/node/pull/48081 to land
=> docs: update maintaining-dependencies.md on major v8 update

lib/ci/failure_aggregator.js
Problems are ignored if they occurred in less than two PRs. Thus, they are reported if they failed in two or more PRs.
https://github.com/nodejs/node-core-utils/blob/ecb1b7d0b86ab2afb581046220e3cfcc6254255a/lib/ci/failure_aggregator.js#L88-L89
=> fix: accurately define ncu-ci report condition

lib/landing_session.js
This pull request properly terminates the CLI issue, but does not fix the unnecessary `Querying for API...` log.
Example output
```
? This PR is not ready to land, do you want to continue? No
⠋ Querying API for job/node-test-pull-request/52248/   ✔  Aborted `git node land` session in /Users/yagiz/Developer/node/.ncu
```
Reference: https://github.com/nodejs/node-core-utils/issues/707
=> fix: properly terminate pr landing sessions

lib/landing_session.js
Commits made using `git commit --fixup=reword:HEAD` are empty commits that lets the user change the commit message without needing to force-push the PR branch. With this commit, those are still ignored when using `--fixupAll` CLI flag.
Another change with this PR is that ncu will no longer reject PRs with empty commits, but will drop them from the rebase. Previously, empty commits were allowed only when using `--fixupAll`.
Tested locally with https://github.com/nodejs/node/pull/48513.
=> feat(git-node): add support for `amend!` commits

components/git/release.js, docs/git-node.md, lib/cherry_pick.js, lib/collaborators.js, lib/prepare_release.js, lib/queries/PRs.gql, lib/utils.js
I'm doing an experiment as part of my work on https://github.com/nodejs/security-wg/issues/860 + upcoming security release.
I was talking with @BethGriggs and looks reasonable to generate the proposal PR for security releases using `git node release --security --prepare 19.6.1`.
Currently, `git node land` doesn't work for the private repo, so the workflow is:
1. Create the proposal branch (based on vX.X instead of staging)
2. Iterate open PRs (based on the given filter) and ask to amend them in the proposal
3. Proceed with the regular workflow (adjust the node_version, changelogs, ...)
Example:
```console
➜  node-private (main) ../node-core-utils/bin/git-node.js release --prepare --security 20.2.1
⚠  Remote repository URL does not point to the expected repository nodejs/node
⚠  You are …
```
=> lib: support security prepare

components/git/v8.js, lib/update-v8/backport.js, lib/update-v8/majorUpdate.js, lib/update-v8/minorUpdate.js, lib/update-v8/updateV8Clone.js, package.json
The less dependencies we have, the better.
=> chore: remove `execa` dependency

components/git/v8.js, lib/update-v8/majorUpdate.js, lib/update-v8/minorUpdate.js, lib/update-v8/updateV8Clone.js
Refs: https://github.com/nodejs/node-core-utils/pull/722#issuecomment-1706027683
Fixes: https://github.com/nodejs/node-core-utils/issues/723
=> fix(v8): fix spawning of subprocesses

components/git/security.js, docs/git-node.md, lib/auth.js, lib/github/templates/next-security-release.md, lib/prepare_security.js, lib/request.js, package.json
This new command should manage all the states of a security release. This PR includes the `CREATE` and should be followed by other PRs to manage the next steps, such as requesting CVEs, creating issues, sending emails and so on.
Example this is action: https://github.com/nodejs-private/node-private/issues/443
=> feat: create security release command

components/git/release.js, docs/git-node.md, lib/prepare_release.js
Adds an option that allows skipping the initial `branch-diff` check step in the release command. This should be very convenient for releasers that are updating a current work in progress proposal, particularly helping avoid hitting GitHub API rate limits.
=> feat(release): add skipBranchDiff option

lib/backport_session.js
Fixes #731
this aligns with steps 1-3 in [`doc/contributing/backporting-to-release-lines.md` - How to submit a backport pull request](https://github.com/nodejs/node/blob/main/doc/contributing/backporting-to-release-lines.md#how-to-submit-a-backport-pull-request)
https://github.com/nodejs/node/blob/c2cd74453e7d2794ad81cab63e68371e08bad04f/doc/contributing/backporting-to-release-lines.md?plain=1#L48-L62
=> fix(backport): checkout from staging branch and ask to update if needed

.github/workflows/release-please.yml, README.md, package.json
Not sure this is ready yet, we may need a new NPM_TOKEN on the repo secret.
Refs: https://github.com/nodejs/TSC/issues/1178
=> chore!: switch to `@node-core` scope

lib/collaborators.js, test/fixtures/README/README.md, test/fixtures/README/README_alternative.md, test/fixtures/README/README_no_TSC.md, test/fixtures/README/README_no_TSCE.md, test/fixtures/README/README_no_collaboratorE.md, test/fixtures/README/README_no_collaborators.md, test/fixtures/README/README_unordered.md, test/unit/collaborators.test.js
Refs: https://github.com/nodejs/node/pull/47126
Refs: https://github.com/nodejs/TSC/pull/1350
BREAKING CHANGE: Old README format is no longer supported
=> fix(git-node): update README parser to account the recent TSC changes

bin/ncu-ci.js, lib/ci/build-types/commit_build.js, lib/ci/build-types/pr_build.js, lib/ci/failure_aggregator.js, lib/links.js
Because it's more useful than the computer URL.
Also use CI URL for PRs instead of the PR URLs themselves.
=> add --skip-more-than to ncu-ci and show console URL for "Appeared on"

lib/run.js, lib/update-v8/updateV8Clone.js
Previously, when the V8 repository was not present, it would emit an `'error'` event instead of rejecting the promise, causing the process to crash instead of running the fallback.
Fixes: https://github.com/nodejs/node-core-utils/issues/743
=> fix(v8): clone V8 repository when it's not present

package.json
Fixes: https://github.com/nodejs/node-core-utils/issues/752
=> fix(ci): use shell expansion to run test files

lib/pr_checker.js, lib/queries/PR.gql, test/fixtures/semver_major_pr.json, test/unit/pr_checker.test.js
The date of a commit is provided by the user, and we should not trust it blindly. Instead, we can check when was the last push event to the PR base branch.
=> fix(node): do not trust committed date

README.md
Update the npm shield in the README to point to the new scoped `@node-core/utils` package instead of `node-core-utils`.
=> fix: update npm shield

lib/github/templates/next-security-release.md, lib/prepare_security.js, lib/request.js
This PR automates the first step of the security release: `security --start`.
The `Next Security Release` issue will not contain the list of reports but they will be stored in the new repository `security-release` in a json format.
This way it will be much easier to automate and manipulate json rather than markdown strings.
@RafaelGSS
=> feat: automate security release issue creation

lib/prepare_security.js
this adds the vector string to report to be used later when requesting cve
=> feat: add vulnerability vector string to json

components/git/security.js, docs/git-node.md, lib/github/templates/security-pre-release.md, lib/security-release/security-release.js, lib/security_blog.js, lib/update_security_release.js
This PR introduces the functionality to create the pre release blogpost
```bash
git-node security --pre-release
```
It will manually prompt if there is a openssl update and add the section without mentioning which specific release lines
=> feat: create pre release blogpost

lib/prepare_security.js, lib/security_blog.js
Fixes: https://github.com/nodejs-private/security-release/issues/13
=> fix: pre-release crashing on missing vulnerability rating

components/git/security.js, lib/security-announcement.js, lib/security-release/security-release.js
This pr allows to automatically create an issue on node-docker repository to announce the security release.
Next step is automate the announcement on google groups
=> feat: automate announcements for pre release

lib/security-announcement.js
Ref: https://github.com/nodejs/build/issues/3666#issuecomment-2025660343
cc: @marco-ippolito
=> fix: add team mention when notifying

components/git/security.js, lib/prepare_security.js, lib/security-announcement.js, lib/security-release/security-release.js, lib/update_security_release.js
Fixes: https://github.com/nodejs-private/security-release/issues/16
Fixes: https://github.com/nodejs-private/security-release/issues/12
@RafaelGSS
=> refactor, feat: patch authors and rebase when pushing 

bin/ncu-ci.js, lib/ci/run_ci.js, lib/pr_checker.js, test/unit/ci_start.test.js, test/unit/pr_checker.test.js
Or ensure the PR has received at least one approving review since last time it was pushed.
=> feat(ncu-ci)!: require `--certify-safe` flag

lib/update-v8/constants.js, lib/update-v8/majorUpdate.js
Also add a custom error message when a dependency disappears to avoid
the unhelpful `Cannot read properties of undefined (reading 'split')`.
Refs: https://github.com/v8/v8/commit/f8fa22073a0db4a62775efba87ddee5f949a2095
=> fix(v8): remove trace_event starting with 12.6

lib/ci/run_ci.js, lib/pr_checker.js, lib/pr_data.js, lib/queries/PRLabeledEvents.gql, lib/queries/PRLabels.gql, test/fixtures/data.js, test/fixtures/first_timer_pr.json, test/fixtures/labeled_events/no-request-ci.json, test/fixtures/labeled_events/old-request-ci-collaborator.json, test/fixtures/labeled_events/recent-request-ci-collaborator.json, test/fixtures/labeled_events/recent-request-ci-non-collaborator.json, test/unit/pr_checker.test.js
When commits were pushed to a PR since the last approving review, check if the last time a `request-ci` label was added, it was done by a Collaborator and after the last push event on the PR.
I don't really like the fact `"request-ci"` is hard-coded, and also it might make sense to enable this check only in the GHA workflow (as the code doesn't search for `'unlabeled'` events, so if someone adds the label and removes it, it would still still count), so if you have suggestions regarding that, I'd be interested.
Fixes: https://github.com/nodejs/node-core-utils/issues/801
=> feat(ncu-ci): check for `request-ci` label

lib/voting_session.js
When the token doesn't have the permission to post the comment directly, we can fallback to showing the user the error message and what command they should type.
=> fix(vote): improve UX when posting comment fails

components/git/security.js, lib/security-release/security-release.js, lib/update_security_release.js
=> feat: create git node security --sync

lib/security-release/security-release.js, lib/update_security_release.js
=> fix: use correct memory address to override

components/git/security.js
Follow up https://github.com/nodejs/node-core-utils/pull/822
=> fix: adjust --post-release description

lib/security_blog.js
We have a CI to check all missing fields before running post-release
=> fix: remove post-release checks

lib/security_blog.js
=> fix: handle dependencies empty on sec release blog

lib/update-v8/applyNodeChanges.js, lib/update-v8/backport.js, lib/update-v8/majorUpdate.js, lib/update-v8/minorUpdate.js, lib/update-v8/updateV8Clone.js, lib/update-v8/updateVersionNumbers.js
Whenever there was a conflict, it was not pausing the previous operation. 
Example repro is
```
git node v8 backport 46ebf52481965305f82a4b75e724282c2ab26a17
```
=> fix: listr overriding parent task

lib/prepare_security.js
Refs: https://github.com/nodejs-private/security-release/issues/35
I have also removed the need to create the Next Security Release issue. We'll use only the PR as tracking.
The https://github.com/nodejs/node/pull/53877 needs to land first.
=> feat: use sec release template in PR description

lib/pr_checker.js
Ref https://openjs-foundation.slack.com/archives/C019MGJQ8RH/p1722871958000979
=> fix: ignore codecov check suite

components/git/security.js, lib/prepare_security.js, lib/request.js, lib/security-release/security-release.js, lib/security_blog.js, lib/update_security_release.js
This adds a final step to cleanup
=> feat: add git node security --cleanup

lib/ci/build-types/citgm_comparison_build.js
Motived by the recent regression on Node.js 22.7.0. Apparently, the CITGM did catch the potential regression on `throughv` package. But, due to the number of failures on CITGM, I somehow missed this module in my analysis: https://github.com/nodejs/node/pull/54452#issuecomment-2302202292.
So, this PR makes sure to include a warning whenever a module fails in **all platforms**. So, the previous CITGM comparison would tell the following:
```
➜  node-core-utils (improve-citgm-summary) ./bin/ncu-ci.js citgm 3468 3471                                                                                                                                                                                ✭ ✱
[1/1] Running CITGM: …
```
=> feat: add warning when fail on all platforms

components/git/release.js, lib/prepare_release.js
As suggested by https://github.com/nodejs/node/pull/53828#discussion_r1676554998
=> feat(git-node): auto-fetch latest release tag when preparing release

lib/prepare_release.js
A few things in the release preparation script were still relying on the local clone to be up-to-date (e.g. to get the Current line (to prepare a LTS release), it relied on the release tag to be present, or when comparing branches). Given preparing a release requires internet access anyway, it seems easy enough to rely on it rather than the local clone.
Testing it from a codespace like this:
```
git clone https://github.com/nodejs/node.git --single-branch --branch=v20.x-staging --no-tags
cd node
../bin/git-node.js release --prepare
```
=> feat(git-node): auto-fetch comparison branch when preparing release

lib/landing_session.js
This allows the `git node land` usage on different forks. It might also help on nodejs-private.
=> fix: landing session on different repo/org

.github/workflows/release-please.yml
- Use new repository for the action
- Use nodejs-github-bot's PAT
- Set minimal permissions for the default token
=> chore: update release-please config

lib/update-v8/minorUpdate.js
Capture stdout so it can be used in the catch block when there is a conflict.
Fixes: https://github.com/nodejs/node-core-utils/issues/850
=> fix(v8): handle error in git apply

bin/ncu-ci.js, docs/ncu-ci.md, lib/cache.js
Previously --cache and --stats were broken (by probably one of the yargs updates) and forced users to use `--stats=true` etc.
Also change the cache location to tmpdir.
=> fix(ncu-ci): fix cache and stats option, and use tmpdir for cache

lib/github/tree.js, test/unit/wpt_updater.test.js
In case of `git node wpt anyUnknownPath`, currently we get a `TypeError: cannot read from undefined`, which is not intuitive.
=> chore(wpt): warn for non-existent wpt path

lib/pr_checker.js, test/fixtures/github-ci/both-apis-failure.json, test/fixtures/github-ci/both-apis-success.json, test/fixtures/github-ci/check-suite-failure.json, test/fixtures/github-ci/check-suite-pending.json, test/fixtures/github-ci/check-suite-skipped.json, test/fixtures/github-ci/check-suite-success.json, test/fixtures/github-ci/status-failure-check-suite-succeed.json, test/fixtures/github-ci/status-succeed-check-suite-failure.json, test/fixtures/github-ci/success-dependabot-queued.json
Implements https://github.com/nodejs/node-core-utils/pull/838#discussion_r1706574660. The problem has come back now that we have a new `jenkins-node-js-ci` (see https://github.com/nodejs/admin/issues/916), and IMO it only makes sense to check for GHA-related jobs only when checking the state of the GitHub CI.
=> fix(git-node): ignore all non-gha nodes when checking for GitHub CI

lib/request.js
=> lib: handle errors on H1 fetch reports

components/git/release.js, docs/git-node.md
This will enable us to automate release proposal
creation: https://github.com/nodejs/security-wg/issues/860
---
I've fixed a few lint nits in the git-node.md too.
=> feat: add --yes option to git node release

lib/prepare_release.js
I hit this when preparing v18.20.5 during the collab summit, it seems like a good idea to use an interaction to help the releaser.
=> feat(git-node): prompt before attempting branch-diff

lib/promote_release.js
I cannot see why we would prefer having several `git push` commands. However, I see a number of reasons to have only one, at the very end of the `--promote` sequence:
- it makes it less likely a release would go half through, e.g. if the releaser has to abandon the release before the `git push` for whatever reason.
- for folks watching the repo, the delay between "the proposal branch gets merged" and "the release tag is out" can be frustrating.
- it removes the need for a `--continue` (cc @RafaelGSS); with this PR, you either have pushed and the only remaining command is `tools/release.sh`, or you haven't pushed and can start over.
=> feat(git-node): use a single `git push` command

lib/promote_release.js
As I was testing `git node release --promote` with https://github.com/nodejs/node/pull/55879, I realized the assumption that a release commit would necessarily conflict when cherry-picked to the default branch is wrong for the case of semver-patch releases.
=> fix(git-node): do not assume release commit will conflict

components/git/v8.js, lib/update-v8/backport.js, lib/update-v8/index.js
It feels wrong to me to take credit when backporting a V8 commit. I see a reason for not cherry-picking the actual commit instead of creating a new one, so this PR is doing that (with a flag to roll back to the previous behavior).
I'm also adding the `-S` flag for those who want to selectively sign commits.
=> feat(git-v8): preserve original author when backporting

components/git/security.js, docs/git-node.md, lib/security_blog.js
Fixes: https://github.com/nodejs-private/security-release/issues/15 & https://github.com/nodejs-private/security-release/issues/18
```
➜  security-release (next-security-release) ../node-core-utils/bin/git-node.js security --pre-release='../nodejs.org'                                                                                            ✱
ℹ  Current branch: next-security-release
✔ When is the security release going to be announced? Enter in YYYY/MM/DD format: 2024/11/28
✔  Announcement file created and banner has been updated. Folder: ../nodejs.org
➜  security-release (next-security-release) cd ../nodejs.org …
```
=> feat: use nodejs.org folder a base for --pre-release

.github/workflows/nodejs.yml
Tokenless uploads are supported again.
Refs: https://docs.codecov.com/docs/codecov-tokens#uploading-without-a-token
=> chore: update codecov action to v5

lib/prepare_release.js
Relevant for the GHA usecase, so we don't have to fetch the whole repo.
=> fix(git-node): support preparing releases on shallow clones

components/git/security.js, docs/git-node.md, lib/security_blog.js
Fixes: https://github.com/nodejs-private/security-release/issues/43
cc: @nodejs/security-release
=> feat: support nodejs org folder on post-release

lib/promote_release.js
Before pushing the tag upstream, we can verify if it's signed with a known identity (name+email address+key combo), as the releaser might be relying on a mailmap entry, which are typically not used when verifying a tag signature (at least not by GitHub web UI).
/cc @nodejs/releasers
=> feat(git-node): verify tag signature during release promotion

package.json
Just to guarantee people will be use a version from changelog-maker that supports CVE-ID
=> feat: update changelog-maker to a CVE-ID support

lib/prepare_release.js
Found this while generating https://github.com/nodejs-private/node-private/pull/654
=> fix: adjust base branch when prepare --security release

lib/security_blog.js
Follow up https://github.com/nodejs/node-core-utils/pull/887
=> fix: use vulnerability as folder for post-release announcement

lib/prepare_release.js
More fixes from upcoming sec release
=> fix: handle UNKNOWN status and lint fix

lib/prepare_security.js, lib/request.js, lib/security-release/security-release.js
Those bugs I found while doing the last security release. I can confirm this patch fixes it.
=> fix: adjust --cleanup

lib/promote_release.js, lib/run.js
During release promotion, we want to verify the tag is signed with one of the releasers' key. The commit can be signed with a different signature (e.g. the bot's, or a soon-to-be releaser).
=> fix(git-node): check the tag signature and not the commit one

lib/prepare_release.js
Partially fixes: https://github.com/nodejs-private/security-release/issues/48
=> lib: use messageonly type when notable-changes sec release

components/git/release.js, lib/promote_release.js
In order to promote a security release using this script:
- your local HEAD should be the release proposal commit
- ncu config **upstream** should point to the **public repo** (NOT the private one)
N.B.: At the end of the process, it won't tell you to push to the private repo, until you do that manually the release proposal won't auto-close.
=> fix(git-node): allow security release promotion

lib/prepare_release.js
This allows for updating a proposal once the proposal branch has already been created, PR opened, e.g:
```sh
git checkout v1.x-staging # go back to the staging branch
git node release -S --prepare 1.y.z # run release prepare script again
```
=> Fix `git node release --prepare` update proposal workflow

lib/ci/run_ci.js, lib/pr_checker.js
I was testing #911, I noticed I would get `No commits found` errors, and indeed it looks like I forgot to change the API call now that we're no longer relying on the PR metadata.
=> fix(ncu-ci): fetch commits instead of PR metadata

lib/pr_checker.js
`findLastIndex` is provided by V8 on all supported Node.js release lines.
`collaboratorEmails` is not read anywhere.
=> chore: remove dead code from `PRChecker`

lib/session.js
NCU expects the local clone to not be shallow, and throws arguably confusing errors when running `git node land` on a shallow clone. We might pass the correct flag if we detect unshallowness.
For a concrete example, that would allow us to use shallow clone in the CQ, and lazy-unshallow only if there are PRs ready to land (currently, if there's a PRs that was open for more than 2 days, and CI is still running, it will cause CQ to fully clone the repo every 10 minutes for nothing).
=> feat(git-node): auto-unshallow shallow clones

lib/prepare_security.js
Very often we add new properties to vulnerabilities.json and having a green ci before merging the PR is a must.
=> fix: mention CI green on security --cleanup

lib/promote_release.js
If there are commits on the staging branch, we probably want to keep them on top of the release commit. Staging branches and release proposal are usually in sync, however it's never the case for security releases.
=> feat(git-node): rebase staging commits after promoting a release

lib/ci/run_ci.js, test/unit/ci_start.test.js
Similar to `node-test-pull-request`, `node-test-commit-v8-linux` also now requires `COMMIT_SHA_CHECK` to be passed to it.
Refs: https://github.com/nodejs/node-core-utils/pull/911
=> fix(ncu-ci): pass `COMMIT_SHA_CHECK` to V8 CI

components/git/wpt.js
adds webcrypto to the list of known interfaces to pull since https://github.com/web-platform-tests/wpt/pull/52264 makes it so the file no longer matches the directory name in webcrypto's case.
=> fix: prepare interfaces updater for updated webcrypto

bin/ncu-ci.js
It's just a flag, the only positional argument is the `<prid>` for `ncu-ci run`.
=> fix(ncu-ci): do not document `--certify-safe` as positional

lib/update_security_release.js
**fix: auto-push git node --security**
```
This change makes git node --security to
auto push the changes to remote. This makes
this feature aligned with other git node security
features that also push to the remote automatically
```
=> fix: auto-push git node --security

README.md
The `https://ci.nodejs.org/user/<your-github-username>/configure` is a 404, instead the url should be
`https://ci.nodejs.org/user/<your-github-username>/security`.
=> docs: update Jenkins token creation link.

lib/wpt/index.js
closes https://github.com/nodejs/node-core-utils/issues/810
I have no idea how to add tests for this, but hopefully it's straightforward. This is needed for undici to use `git node wpt` to pull tests for its runner.
=> batch requests in wpt

components/git/release.js, lib/promote_release.js
And from a different remote. Currently, the `git node release --promote` workflow doesn't work well for security releases as it assumes the release proposal exists on the same repo as where we want to make the release, and releases are to be released one-by-one.
This PR aims at addressing all this shortcomings.
The process is now roughly:
1. for each proposal PR:
1. Verify if it's ready (correct date, changelog entry, etc.).
2. Create a signed tag for it.
3. create a `Working on …` commit.
4. rebase the public staging branch.
2. checkout the default branch, and cherry-pick all releases commit on top of it.
3. Print out a single `git push` command to push everything at once to the public repo.
4. Rest of the workflow is not affected.
I've tested this with 24.1.0 and 22.16.0, seems to work …
=> feat(git-node): add support for promoting several releases at once

lib/voting_session.js
Useful when piping to another command. E.g., `git node vote <url> --decrypt-key-part 2>/dev/null` reveals the key without any other output.
=> fix(git-node): output vote keyPart to stdout, not stderr

lib/cherry_pick.js, lib/landing_session.js, lib/prepare_release.js, lib/promote_release.js, lib/session.js, lib/voting_session.js
An oversight from https://github.com/nodejs/node-core-utils/pull/917.
=> fix(git-node): correctly pass values to `CherryPick`

lib/security_blog.js
Fixes: https://github.com/nodejs-private/security-release/issues/63
=> feat: update announcement link on --pre-release

lib/update_security_release.js
Refs: https://github.com/nodejs-private/security-release/issues/64
=> feat: add patchedVersions on --request-cve

bin/ncu-ci.js
When trying to run CIs on unapproved PRs, it's a bit annoying to have to split the info myself when the URL I copy from the web UI already contains all the requested info.
=> feat(ncu-ci): accept URLs in `ncu-ci run`

lib/voting_session.js
Fixes: https://github.com/nodejs/TSC/pull/1770#issuecomment-3103074002
In 1263d0f07457d6c8f9f9720caa24227a2ba66621, we moved the logic to the parent `Session` class so we can use it for other kind of sessions, however Caritat already has internal logic to handle that flag, so we should just pass the value directly
=> fix(git-node): pass `-S` flag directly to Caritat

README.md, lib/config.js
Rely on `gpg` being available on the path, but is opt-in so it shouldn't be a problem. Users can chose wether they want to use a  passphrase or their key pair, and that should be completely transparent for ncu.
Fixes: https://github.com/nodejs/node-core-utils/issues/615
=> feat: add support for PGP encrypted config files

.github/workflows/release-please.yml
Refs: https://github.com/nodejs/admin/issues/998
=> chore: enable OIDC package publishing

lib/config.js
I kinda forgot I moved to encrypted config file, and got surprised to be asked for my passphrase. Adding a warning so next time I forget, I won't be surprised.
=> fix: add warning before spawning `gpg`
